### PR TITLE
rename keccak

### PR DESCRIPTION
**Pull request by tanishqjasoria**
With verkle tree, we would be using Pedersen in instead of Keccak for state related operations. 
Also there are other chains, that we plan to support, using differnet commitment schemes (For eg. poseidon).
This PR replaces Keccak with a more generic class Commitment that can be used to represent any commitment scheme (32 bytes).

## Changes

- rename Keccak -> Commitment, ValueKeccak -> ValueCommitemnt, KeccakStructRef -> CommitmentStructRef
- seperate the representation and computation of Keccak.

#### What types of changes does your code introduce?

- [ ] Bugfix (a non-breaking change that fixes an issue)
- [ ] New feature (a non-breaking change that adds functionality)
- [ ] Breaking change (a change that causes existing functionality not to work as expected)
- [ ] Optimization
- [x] Refactoring
- [ ] Documentation update
- [ ] Build-related changes
- [ ] Other: _Description_

#### Requires testing

- [x] Yes
- [ ] No

#### If yes, did you write tests?

- [ ] Yes
- [x] No

#### Notes on testing

Current unittest already cover this properly

#### Requires documentation update

- [ ] Yes
- [x] No

#### Requires explanation in Release Notes

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by tanishqjasoria** [comment]
https://github.com/NethermindEth/nethermind/pull/6197/files#diff-126685825e25ecfb16e932661d002ae93a9a4b630fc6aba8cf79c9201726c397

https://github.com/NethermindEth/nethermind/pull/6197/files#diff-a8b151e18c2db3d54234d51fe2fed07f325470326500bb87e44d9cff6c44b4fb

these are the two files that are the important - rest almost everthing is result of renaming.

**Comment by benaadams** [comment]
Why `Commitment`?

That seems more for what its used for (i.e. variable name) than what it is (i.e. class name)

Pedersen is also a Hash; as is Poseidon; would generic `Hash` be better?

I may have this wrong, but I think a [Commitment scheme](https://en.wikipedia.org/wiki/Commitment_scheme) can use hashes, but a [Cryptographic hash function](https://en.wikipedia.org/wiki/Cryptographic_hash_function) is not necessarily part of a Commitment scheme?

**Comment by tanishqjasoria** [comment]
> +1 for `Hash` or even better `Hash256`?

or Hash32?

**Comment by asdacap** [comment]
I vote for Hash256.

**Comment by tanishqjasoria** [comment]
renamed to Hash256, ready for a review!

**Review by LukaszRozmej — APPROVED** [review]

**Review by asdacap — APPROVED** [review]

**Pull request merged**
