### PR TITLE
Do not save stateroot in snap phase 1

### LINKED ISSUE #4831: [1.14.4] After upgrading from 1.14.3 synced with FastSync to 1.14.4 and enabling SnapSync, SNAP Phase1 is starting
**Describe the bug**
According to users from discord, on already synced nodes users when upgrading to 14.4 from 14.3 experience a logs SNAP Phase1 which should not be visible when node is fully synced.
As for now I was able to reproduce this once with Sepolia chain

**To Reproduce**
1. On 1.14.3 Start syncing Sepolia with --Sync.SnapSync=false
2. Wait until state sync will finish and node will move to "OldBodies"
3. Stop a node
4. Switch to 1.14.4 with the same run command BUT with --Sync.SnapSync=true
5. Start node and monitor

**Expected behavior**
Sync should start from exactly the same spot without changing stage.
In my case I've started noticing SNAP Phase1 logs.
Seems like after repeated snap sync node is progressing well but it should not happen.

[sepolia.logs.txt](https://github.com/NethermindEth/nethermind/files/9880665/sepolia.logs.txt)

### PR DESCRIPTION
**Pull request by asdacap**
Fixes #4831

- The sepolia fix now depends on snap range flag being stored to prevent it from restarting snap range as snap range is enabled at start up.
- This remove the sepolia fix and prevent snap ranges from saving state root.

## Changes:
- Revert sepolia fix.
- Add flag to skip saving state root on snap range.

## Types of changes

What types of changes does your code introduce?
_Put an `x` in the boxes that apply_

- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Other (please describe): 

## Testing
**Requires testing**

- [X] Yes
- [ ] No

**In case you checked yes, did you write tests??**

- [ ] Yes
- [X] No

**Comments about testing , should you have some** (optional)

- Confirm sepolia issue is still reproducable if root hash was set.
- With change, can sync up to validating block 5 consecutive time.

## Further comments (optional)

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by LukaszRozmej — APPROVED** [review]

**Comment by kamilchodola** [comment]
@asdacap 
I'm in the middle of syncing all chains possible and seems like it is better - no exceptions on Sepolia and it is already done with 4 CLs so I can see an improvement for sure.

Will wait fora moment for other chains to complete also to see if there is no impact on them.

**Comment by kamilchodola** [comment]
@asdacap 
From my smoke tests seems fine for now - But did You have a chance to run any POSDAO/Hive tests for this PR? If not maybe we should do this before merging.

**Comment by kamilchodola** [comment]
Just to be sure I have started POSDAO and Hive to check the results before merging.

**Review by kamilchodola — APPROVED** [review]
Hive and POSDAO green. Approving

**Pull request merged**
