### PR TITLE
Improve JSON config files

### PR DESCRIPTION
**Pull request by MysticRyuujin**
1. Fix formatting of Config Files

- The JSON formatting was all over the place.
- There were errors in xdai configs (trailing commas)

2. Increase mainnet pivot block to something more recent

### CODE REVIEW

**Comment by tkstanczak** [comment]
@MysticRyuujin I think it was literally automated recently...

**Comment by tkstanczak** [comment]
we now auto-create a PR with newer fast blocks pivot block for each network:
https://github.com/NethermindEth/nethermind/pull/1570/files

**Comment by MysticRyuujin** [comment]
That doesn't address the first concern. I can patch to match the pivot numbers. Or you guys can auto format your JSON

**Comment by MysticRyuujin** [comment]
Ok my config files now match #1570 pivots...

**Comment by MysticRyuujin** [comment]
Formatting aside, there's still errors on the xdai stuff (trailing commas).

**Pull request closed without merging**
