### PR TITLE
Add status checks for tools

### PR DESCRIPTION
**Pull request by rubo**
## Changes

Added build status checks for the projects in the `tools` directory.

#### What types of changes does your code introduce?

- [ ] Bugfix (a non-breaking change that fixes an issue)
- [ ] New feature (a non-breaking change that adds functionality)
- [ ] Breaking change (a change that causes existing functionality not to work as expected)
- [ ] Optimization
- [ ] Refactoring
- [ ] Documentation update
- [ ] Build-related changes
- [x] Other: Status checks

#### Requires testing

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by rubo** [comment]
Currently, SendBlobs and TxParser fail to compile.

**Review by LukaszRozmej — APPROVED** [review]

**Comment by LukaszRozmej** [comment]
@ak88 @smartprogrammer93 @marcindsobczak can you fix those tools?

**Comment by ak88** [comment]
> @ak88 @smartprogrammer93 @marcindsobczak can you fix those tools?

Here you go
https://github.com/NethermindEth/nethermind/pull/7579

**Comment by ak88** [comment]
> @ak88 you were 1min faster 😄 #7580

My girlfriend says the same 🥇 😄

**Review by MarekM25 — APPROVED** [review]

**Pull request merged**
