### PR TITLE
Reduce memory for GetPayloadBodiesByRangeV1 and GetPayloadBodiesByHashV1

### PR DESCRIPTION
**Pull request by benaadams**
## Changes

- Use full enumerator rather than building List for block bodies

#### What types of changes does your code introduce?

- [ ] Bugfix (a non-breaking change that fixes an issue)
- [ ] New feature (a non-breaking change that adds functionality)
- [ ] Breaking change (a change that causes existing functionality not to work as expected)
- [x] Optimization
- [ ] Refactoring
- [ ] Documentation update
- [ ] Build-related changes
- [ ] Other: _Description_

#### Requires testing

- [ ] Yes
- [x] No

#### If yes, did you write tests?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by LukaszRozmej** [comment]
The only potential downside is that if it fails to find non-first block it will first start streaming the results, ending in invalid json response

**Comment by MarekM25** [comment]
> The only potential downside is that if it fails to find non-first block it will first start streaming the results, ending in invalid json response

@LukaszRozmej any propositions?

**Comment by LukaszRozmej** [comment]
> > The only potential downside is that if it fails to find non-first block it will first start streaming the results, ending in invalid json response
> 
> @LukaszRozmej any propositions?

ah I might have read it wrong, we just output null's on not found, should be fine then

**Review by LukaszRozmej — APPROVED** [review]

**Comment by kim201212** [comment]
Thank you for your PR.
 I really appreciate this optimization, it's exactly what I needed. 👍

**Pull request merged**
