### PR TITLE
Switch to NUnit v4

### PR DESCRIPTION
**Pull request by rubo**
## Changes

Migrated to NUnit v4:

- Replaced `Assert.<Method>()` assertions with `Assert.That()` assertions
- Replaced `CollectionAssert` assertions with `Assert` assertions
- Replaced `TestContext.WriteLine` with`TestContext.Out.Write`
- Replaced obsolete `TimeoutAttribute` with `MaxTimeAttribute`

#### What types of changes does your code introduce?

- [ ] Bugfix (a non-breaking change that fixes an issue)
- [ ] New feature (a non-breaking change that adds functionality)
- [ ] Breaking change (a change that causes existing functionality not to work as expected)
- [ ] Optimization
- [x] Refactoring
- [ ] Documentation update
- [ ] Build-related changes
- [ ] Other: _Description_

#### Requires testing

- [x] Yes
- [ ] No

#### If yes, did you write tests?

- [x] Yes
- [ ] No

## Remarks

With this upgrade, the FluentAssertions package doesn't seem needed.

### CODE REVIEW

**Review by LukaszRozmej — APPROVED** [review]

**Comment by LukaszRozmej** [comment]
Will `CancelAfter` fail the test?

**Comment by rubo** [comment]
> Will `CancelAfter` fail the test?

@LukaszRozmej That's a good question. It won't. Actually, as the `Timeout` is gone, there are 2 other options—`MaxTime` and `CancelAfter`. `MaxTime` fails the test if the test exceeds the time limit. But it lets the test run as long as it takes and then checks the actual duration. `CancelAfter` is for canceling long-running tasks with a cancellation token, but most of our test APIs don't support that.
With this said, we better use `MaxTime` instead of `CancelAfter`.

**Comment by LukaszRozmej** [comment]
Maybe we should add both?

**Comment by rubo** [comment]
> Maybe we should add both?

In some cases, yes. But our API doesn't support it. Modifying it would bring many cascading changes, which I'd like to avoid in this PR. Another issue is overkill with timeouts. [Check this out](https://github.com/NethermindEth/nethermind/blob/master/src/Nethermind/Nethermind.Blockchain.Test/Consensus/CompositeTxSourceTests.cs#L19), for instance. Why do we need a timeout there? There are a bunch of such examples.

**Pull request merged**
