### PR TITLE
Move keys to keyStoreDirectory

### LINKED ISSUE #4305: Nethermind ignores --datadir for keys
**Describe the bug**
I run the latest `nethermindeth/hive:latest` and it for some reason needs to write files into the /nethermind/Nethermind folder

```
# ls
key-84e57e41-999d-4152-aadd-9efc5c1dbfc5.xml
# pwd
/nethermind/Nethermind
```

**To Reproduce**
1. Run Nethermind in the container with `--datadir  /data/nethermind`
2. Let it start.
3. `exec` into container, and cd `/nethermind/Nethermind` and you will see 
```
# ls
key-84e57e41-999d-4152-aadd-9efc5c1dbfc5.xml
# pwd
/nethermind/Nethermind
```

**Expected behavior**
Keystore keys are also generated in `--datadir` or at least there is parametrization for that.

### PR DESCRIPTION
**Pull request by deffrian**
Fixes | Closes | Resolves
#4305 

## Changes:
- Protection keys moved from SpecialFolder to keyStoreDirectory

## Types of changes

What types of changes does your code introduce?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Other (please describe): 

## Testing
**Requires testing**

- [x] Yes
- [ ] No

**In case you checked yes, did you write tests??**

- [x] Yes
- [ ] No

### CODE REVIEW

**Review by LukaszRozmej — COMMENTED** [review]
Is it backwards compatible?

**Comment by deffrian** [comment]
> Is it backwards compatible?

No, it will generate new keys in keystore directory

**Comment by MarekM25** [comment]
> > Is it backwards compatible?
> 
> No, it will generate new keys in keystore directory

So I guess we can't work in this way

**Review by attila-lendvai — COMMENTED** [review]
there are excessive whitespace changes in the commits, which makes reviewing and tracking the change/commit history harder.

**Review by attila-lendvai — COMMENTED** [review]
[deleting accidental double post]

**Comment by attila-lendvai** [comment]
FTR, i'm bitten by this on Guix, i.e. a non-docker based setup.

**Comment by tkstanczak** [comment]
@matilote

**Review by damian-orzechowski — APPROVED** [review]

**Pull request merged**
