### PR TITLE
feat: add CentralPackageVersions management

### PR DESCRIPTION
**Pull request by xas**
## Changes:

* centralize nuget package management (see [CentralPackageVersions](https://github.com/microsoft/MSBuildSdks/tree/main/src/CentralPackageVersions))
* add _Directory.Build.targets_ file
* add _Packages.props_ file
* !update of all the packages to their latest version

The purpose of this PR is to keep all the projects using the same nuget package version (avoid inconsistency) and be able to globally update a package version without parsing all the projects/solutions

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update
- [x] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Other (please describe): 

## Testing
**Requires testing**

- [ ] Yes
- [x] No

**In case you checked yes, did you write tests??**

- [ ] Yes
- [x] No

## Further comments (optional)

As I updated all the nuget packages, maybe some testing are needed to verify new version don't cause any regressions, plus need to check on submodules also

### CODE REVIEW

**Comment by LukaszRozmej** [comment]
Might be good, but needs thorough review I will take a look after merge is being finalized. Maybe someone else can take a look earlier.

**Comment by xas** [comment]
> Also: https://www.mytechramblings.com/posts/centrally-manage-nuget-versions/

Yup, I read this one, I thought the nuget solution was the good one, but as the team define the functionality as still in preview, I've gone for the simpler one, and the migration seems easy (only need to rename _Packages.props_ to _Directory.Packages.props_ , or I missed a part ?)

**Comment by rubo** [comment]
With the release of .NET 7, we can move to the central package management once the project initial migration is done and dusted.

**Comment by LukaszRozmej** [comment]
> With the release of .NET 7, we can move to the central package management once the project initial migration is done and dusted.

Feel free to do that :)

**Comment by rubo** [comment]
@xas Thank you much for the idea. Closing in favor of #5314.

**Pull request closed without merging**
