### PR TITLE
Update RocksDB package

### PR DESCRIPTION
**Pull request by rubo**
## Changes

 - Updated the RocksDB package to the v8.3.2.
 - Updated other packages (no major updates)

#### What types of changes does your code introduce?

- [ ] Bugfix (a non-breaking change that fixes an issue)
- [x] New feature (a non-breaking change that adds functionality)
- [ ] Breaking change (a change that causes existing functionality not to work as expected)
- [ ] Optimization
- [ ] Refactoring
- [ ] Documentation update
- [ ] Build-related changes
- [ ] Other: _Description_

#### Requires testing

- [x] Yes
- [ ] No

#### If yes, did you write tests?

- [ ] Yes
- [x] No

#### Notes on testing

Tested manually for backward- and forward-compatibilities.

#### Requires documentation update

- [ ] Yes
- [x] No

#### Requires explanation in Release Notes

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by LukaszRozmej — APPROVED** [review]
Tests? Sync?

**Comment by rubo** [comment]
> Tests? Sync?

@LukaszRozmej Yes, both.

**Review by benaadams — APPROVED** [review]

**Comment by LukaszRozmej** [comment]
> > Tests? Sync?
> 
> @LukaszRozmej Yes, both.
Improvements? Regressions?

**Comment by rubo** [comment]
Didn't notice any regressions. Possibly some slight improvements.

**Pull request merged**
