### PR TITLE
Update supported networks

### PR DESCRIPTION
**Pull request by rubo**
## Changes

Updated supported network list in README. Added Base, JOC, Optimism. Removed non-Ethereum testnets to keep the file concise.

#### What types of changes does your code introduce?

- [ ] Bugfix (a non-breaking change that fixes an issue)
- [ ] New feature (a non-breaking change that adds functionality)
- [ ] Breaking change (a change that causes existing functionality not to work as expected)
- [ ] Optimization
- [ ] Refactoring
- [x] Documentation update
- [ ] Build-related changes
- [ ] Other: _Description_

#### Requires testing

- [ ] Yes
- [x] No

#### If yes, did you write tests?

- [ ] Yes
- [x] No

#### Requires documentation update

- [ ] Yes
- [x] No

#### Requires explanation in Release Notes

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by LukaszRozmej — COMMENTED** [review]
Are you sure about the order?
Are we removing Chiado and Volta?
Are we officially supporting JOC?

**Comment by rubo** [comment]
@LukaszRozmej 

- Ordering is simply alphabetical after Ethereum stuff
- Non-Ethereum testnets were removed to keep the README concise as indicated in the description. With upcoming Base, OP, and JOC testnets it would be too much for this README. It's obvious, that if the mainnet is supported, testnets are as well. For those who want to check, the docs have the full list.
- Not sure about official/not-official. Will check.

**Comment by rubo** [comment]
JOC removed.

**Review by MarekM25 — CHANGES_REQUESTED** [review]
Why did you remove Volta and Chiado?

**Pull request closed without merging**
