### PR TITLE
Simplify updating metrics

### PR DESCRIPTION
**Pull request by LukaszRozmej**

### CODE REVIEW

**Review by asdacap — APPROVED** [review]

**Comment by LukaszRozmej** [comment]
@asdacap will the names keep being ok? I went from (string, string) tuple in dictionary keys to just struct with ToString

**Comment by asdacap** [comment]
Yea, thats the modification to the metric that I mentioned. Now it won't have the protoocl label, just the message type (the .ToString()). Need to modify the metric code so that it knows this struct represent two label instead of only one.

**Comment by asdacap** [comment]
Just merge it, I'll add it later.

**Comment by LukaszRozmej** [comment]
Ok @benaadams can you also advise on the struct? I wanted to make it readonly, but the `_name` is looked up on demand, any ideas how to do it better?

**Pull request merged**
