### PR TITLE
Files db

### PR DESCRIPTION
**Pull request by Scooletz**
This PR proposes a new replacement for a RocksDB, a simple File DB. It's based on logs, memory mapped files and knowing the structure and distribution of the key and values (32 bytes, uniform). It also takes into consideration that data are not removed and they are mostly used in LRU manner. The implementation still requires polishing, but in Goerli based tests received much better results than Rocks on my machine.

This work is somewhat inspired by Microsoft's [FASTER](https://github.com/microsoft/FASTER) but requires no session management, is coherent with the existing Nethermind API and is only 1000 lines long (at least for now).

## Benchmarks

Goerli with  `--config configs\goerli.cfg --Sync.DownloadBodiesInFastSync false --Sync.DownloadReceiptsInFastSync false -- Sync.DownloadHeadersInFastSync false`

- saved on disk in `1h` and a few minutes
- `diagnostics` time from logs was rising from `1.8ms` do `2.3ms` at the end (no Blooms yet!)
- state size on the disk `~8GB`
- Runners memory usage `~1.8 GB`

Final logs from syncing

```
2021-07-09 22:32:38.7239|State Sync 00.01:06:15 | ~100,00% | 4749,65MB / ~4725,00MB | branches: 60,94% | kB/s:  3145 | accounts 4206639 | nodes 58944140 | diagnostics: 20.2,31ms
2021-07-09 22:32:39.7451|State Sync 00.01:06:16 | ~100,00% | 4752,08MB / ~4725,00MB | branches: 60,94% | kB/s:  2383 | accounts 4208692 | nodes 58974660 | diagnostics: 21.2,31ms
```

### Persistent Log

The implementation introduces a `PersistentLog`. A circular buffer, that flushes half of its content as a file once it's filled and maps it using the memory mapped file. This allows using only twice as memory as a declared chunk size and delegate the rest to the system. The memory mapped files are not flushed as in previous PRs that I provided. They are just mapped and should be used for reading purposes only. This should lower the pain with flushing the view, where when a view if flushed, on various OSes all of the pages might be trashed from the page cache. `PersistentLog` provides a way of appending a `Span<byte>` and receiving its `long` identifier. This means that a db value can be mapped to a `long` and mapped to the key in another structure.

The persistent log is used for two different purposes with two different file extensions:

- `*.log` - used for storing values, mapping the value to a `long` value that it can be retrieved with
- `*.keys` - used for providing storage for the persistent version of the `KeccakMap`. They map map's entries to their `long` identifiers

### Keccak Map

The underlying DB is based on a `KeccakMap` that in both flavors (persistent and in memory) maps `Keccak -> long`. The mapping is done in buckets, and each bucket contains a linked list of entries that maps to another entry within the same bucket. Buckets are defined as a bit mask over the key, so again, they should be uniformly distributed. The new entries are added on top of the bucket ensuring LRU behavior. For now, buckets do not have `Bloom` filters. This feature can be added to speed up searching for the non existing keys.

An important fact of the persistent `KeccakMap` is that it's implemented on top of the `PersistentLog`. An entry is added to a `*.log` and its `long` identifier is returned. Walking the list of entries is started with a long which is mapped to an entry which points to another `long` which points to another entry. This allows to keep only a managed `long[]` and have everything else delegated to the persistent log. Including flushing, memory mapping etc. One trick that is used is that the `Entry` is read with `Unsafe.Read` as the memory, both the whole log as each entry, is properly aligned to word boundaries.

### Batch

The batch implementation is a bit... fast. The trick that is used to ensure that data are not copied twice is based on the fact that for storing values the actual persistent log is used. This means that in a case of batch being not committed, the log will contain data that are not reachable. As this is not a common case, storing data directly in the persistent log saves a lot of copying and ensures that memory is not occupied with copies of data. This speeds up the commit process as well because the only part that is required is coping the in-memory `KeccakMap` to the persistent one.

The in-memory map is cleared after a batch finishes and its instance can be reused for future batches. This prevents being overly allocatey.

## TODO

A shutdown procedure where a half written log is flushed and recovery. This can be added with some checkpoints and ensuring that the db can read a partially written file.

Restart at all. Currently db won't memory map existing files. It will probably crash.

All of the above can be implemented but as they require a bit more effort, a good benchmark on various OSes is required. We were been burnt in the bast due to being overly optimistic and I'll do my best to test it first before spending more than needed.

## Types of changes

What types of changes does your code introduce?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update
- [ ] Code style update (formatting, renaming)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Other (please describe): 

## Testing
**Requires testing**

- [x] Yes
- [ ] No

**In case you checked yes, did you write tests??**

- [ ] Yes
- [ ] No
- [x] Some

### CODE REVIEW

**Comment by matilote** [comment]
# Benchmarking scenario

Running 2 simultaneous `goerli` fast syncs without Headers, Receipts and Bodies - one on the `master` branch and one on  this PR base branch.

# Hardware spec
- 4x vCPU AMD
- 8 GB RAM
- Ubuntu 20.04

# Benchmarking results

### Db Size
| FilesDB        | RocksDB           |
| :-------------: |:-------------:| 
| state: **11 GB** | **9.1 GB** | 

## Round 1

### Time

| FilesDB        | RocksDB           |
| :-------------: |:-------------:| 
| real: **69m 31.915s** | **64m33.740s** | 
| user: 41m12.255s | 66m15.775s  | 
| sys: 7m47.188s | 10m21.526s  |

### Graphs
| FilesDB        | RocksDB           |
| :-------------: |:-------------:| 
| image | image | 


## Round 2

### Time
| FilesDB        | RocksDB           |
| :-------------: |:-------------:| 
| real: **89m56.656s** | **94m52.403s** | 
| user: 44m14.381s | 71m32.267s  | 
| sys: 7m37.680s | 12m6.029s  |

### Graphs
| FilesDB        | RocksDB           |
| :-------------: |:-------------:| 
| image | image |

**Comment by Scooletz** [comment]
Thank you @matilote for the awesome benchmarks! Let me wrap my head around it.

A few remarks:

1. As RocksDB does it's merges on SST files, IOPS and CPU will be higher for sure. FileDb does not do any kind of compaction and follows write once mantra using its log files as the primary and only storage. 
2. As there's no compaction, files for FileDb will be bigger for sure. Each key and value are additionally aligned to 8-byte boundary with FileDb and each is prefixed with 8 bytes header. This adds 25% for storing the keys and some additional overhead for storing the values (which, if were 1 bytes long, would have 15 bytes penalty). This penalty shouldn't be big but it's visible in the output size. This might be worked on.
3. It's not bad is it? I mean, if I compare that to previous endeavors, it looks quite reasonable 👀

**Comment by LukaszRozmej** [comment]
Can we run this on mainnet? I am wondering about seek times when processing blocks.

**Comment by matilote** [comment]
> Can we run this on mainnet? I am wondering about seek times when processing blocks.

Seeing this on `mainnet`

```
2021-07-13 10:14:59.7736|Step LoadGenesisBlock         failed after 119ms System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Nethermind.Db.Files.InMemoryKeccakMap.Put(Int64 key0, Int64 key1, Int64 key2, Int64 key3, Int64 value) in /root/src/nethermind/src/Nethermind/Nethermind.Db.Files/InMemoryKeccakMap.cs:line 99
   at Nethermind.Db.Files.InMemoryKeccakMap.Put(Byte[] key, Int64 value) in /root/src/nethermind/src/Nethermind/Nethermind.Db.Files/InMemoryKeccakMap.cs:line 94
   at Nethermind.Db.Files.Db.Batch.set_Item(Byte[] key, Byte[] value) in /root/src/nethermind/src/Nethermind/Nethermind.Db.Files/Db.cs:line 128
   at Nethermind.Trie.Pruning.TrieStore.Persist(TrieNode currentNode, Int64 blockNumber) in /root/src/nethermind/src/Nethermind/Nethermind.Trie/Pruning/TrieStore.cs:line 658
   at Nethermind.Trie.Pruning.TrieStore.CommitNode(Int64 blockNumber, NodeCommitInfo nodeCommitInfo) in /root/src/nethermind/src/Nethermind/Nethermind.Trie/Pruning/TrieStore.cs:line 247
   at Nethermind.Trie.PatriciaTree.Commit(Int64 blockNumber) in /root/src/nethermind/src/Nethermind/Nethermind.Trie/PatriciaTree.cs:line 159
   at Nethermind.State.StateProvider.CommitTree(Int64 blockNumber) in /root/src/nethermind/src/Nethermind/Nethermind.State/StateProvider.cs:line 810
   at Nethermind.Blockchain.GenesisLoader.Load() in /root/src/nethermind/src/Nethermind/Nethermind.Blockchain/GenesisLoader.cs:line 68
   at Nethermind.Runner.Ethereum.Steps.LoadGenesisBlock.Load() in /root/src/nethermind/src/Nethermind/Nethermind.Runner/Ethereum/Steps/LoadGenesisBlock.cs:line 77
   at Nethermind.Runner.Ethereum.Steps.LoadGenesisBlock.Execute(CancellationToken _) in /root/src/nethermind/src/Nethermind/Nethermind.Runner/Ethereum/Steps/LoadGenesisBlock.cs:line 55
   ```

**Comment by Scooletz** [comment]
@matilote I added a dummy commit, increasing the batch to `512 * 1024` items (I hope this is ok) in https://github.com/NethermindEth/nethermind/pull/3212/commits/aebba84430db0a51957b0d2a91e4a28365f64794 This might be fixed later to make it more adjustable, wanted to give it a spin and will provide later on top of it.

**Comment by Scooletz** [comment]
@matilote @LukaszRozmej 

In the last two commits I added two simple fixups that should enable testing this change on mainnet. They are not production ready, but aim solely in helping with validating the idea. The first in https://github.com/NethermindEth/nethermind/pull/3212/commits/aebba84430db0a51957b0d2a91e4a28365f64794, addresses the size of the batch that was throwing, making it very big (25MB of managed memory used), the second https://github.com/NethermindEth/nethermind/pull/3212/commits/c6b80a966ba565e009e4c7f1ecd9443f0a14d929, introduces a disposal that writes a checkpoint. This was the error thrown when the Beam Sync was ending. 

Both should be reviewed and highly likely rewritten, but they should bring us closer to have a mainnet node running with a new db which would be aligned with remarks made above. If I could just ask to not kill the node as still, it might not recover properly, it'd be great.

The final note: I can see all ✔️ in the suite. Does this makes it ready for a mainnet test? 😃

**Comment by tkstanczak** [comment]
@matilote we should have a test for PRs which starts a spaceneth with a DB and then restarts it with the same DB and checks if the values can be read via JSON RPC -> maybe some intern can do that?
this should crash with this commit

**Comment by matilote** [comment]
# MacOS Benchmarks

# Benchmarking scenario

Running 2 simultaneous `goerli` fast syncs without Headers, Receipts and Bodies - one on the `master` branch and one on this PR base branch.

FilesDB - `1.10.73-32-67092685d-20210713/X64-macOS/5.0.8`
RocksDB - `1.10.77-5-b77414d79-20210713/X64-macOS/5.0.7`

# Hardware spec
- mac1.metal
- 12x vCPU
- 32 GB RAM
- MacOS Big Sur 11.4

# Benchmarking results
[FilesDB logs](https://github.com/NethermindEth/nethermind/files/6811086/goerli-filesdb.txt)

### Avarage diagnostics
| FilesDB        | RocksDB           |
| :-------------: |:-------------:| 
| **~1.55ms** | **~6.20ms** | 

### Db Size
| FilesDB        | RocksDB           |
| :-------------: |:-------------:| 
| state: **11 GB** | state: **9.0 GB** | 

### Time
| FilesDB        | RocksDB           |
| :-------------: |:-------------:| 
| real: **55m 54.53s** | **67m 53s** | 
| user: 1639.46s | 2604.49s  | 
| sys: 505.71s | 725.05s |

**Comment by Scooletz** [comment]
>
> @matilote we should have a test for PRs which starts a spaceneth with a DB and then restarts it with the same DB and checks if the values can be read via JSON RPC -> maybe some intern can do that?
> this should crash with this commit

Yes, this PR is not fault-proof yet and the checkpoint introduced was a poor man's solution to ensure that it has any ability to be restarted gracefully (Beam Sync does that). As the numbers are coming from various runs it's becoming more and more tempting though to have it optimized and polish its implementation.

**Comment by matilote** [comment]
The first `mainnet` test run was running head to head on both branches. It slowed down drastically on this PR branch at ~7 GB state and kept creeping very slowly.
image

**Comment by Scooletz** [comment]
Thank you for running these @matilote ! Will take a look!

**Comment by matilote** [comment]
@Scooletz attaching logs from the last run on `files-db`:

[mainnet.logs.txt](https://github.com/NethermindEth/nethermind/files/6821668/mainnet.logs.txt)

**Comment by Scooletz** [comment]
I followed up the logs and I can confirm that the approach proposed in this PR, even if it's okish for the short term proves to be equally bad for bigger dbs as the previous ones, showing the same detrimental long-term nature.

 I'm closing it now. Some parts maybe will be used in the future, but for now, let's pause and not burn more time on it.

**Comment by Scooletz** [comment]
Reopening to look at it for one thing.

**Comment by Scooletz** [comment]
Closing. Not pursuing this approach now.

**Pull request closed without merging**
