### PR TITLE
Check branch name for uppercase

### PR DESCRIPTION
**Pull request by flcl42**
Stop building if branch contains upper case letters

#### What types of changes does your code introduce?

- [ ] Bugfix (a non-breaking change that fixes an issue)
- [ ] New feature (a non-breaking change that adds functionality)
- [ ] Breaking change (a change that causes existing functionality not to work as expected)
- [ ] Optimization
- [ ] Refactoring
- [ ] Documentation update
- [x] Build-related changes
- [ ] Other: _Description_

### CODE REVIEW

**Comment by Demuirgos** [comment]
Can we stop push command itself from working?

**Review by LukaszRozmej — COMMENTED** [review]
Not really that helpful as the branch is already there

**Comment by flcl42** [comment]
@LukaszRozmej the idea is that it will break locally before push. But it does not prevent pushing indeed

**Review by smartprogrammer93 — APPROVED** [review]

**Comment by smartprogrammer93** [comment]
git hooks?

**Comment by smartprogrammer93** [comment]
Honestly, i would still merge it, even if it will not fully prevent it

**Review by rubo — COMMENTED** [review]
I don't think we really need this.

**Comment by smartprogrammer93** [comment]
@rubo I dont see how it would hurt to have it

**Comment by LukaszRozmej** [comment]
Maybe the solution is making this case sensitive on Windows? 

https://stackoverflow.com/a/69742274

**Review by marcindsobczak — APPROVED** [review]

**Comment by flcl42** [comment]
> Maybe the solution is making this case sensitive on Windows?
> 
> https://stackoverflow.com/a/69742274

It requires directory to be empty, then you can clone into it or move an existing repo I guess, which is not very convenient

**Pull request merged**
