### PR TITLE
Refactor/dependency injection 2

### PR DESCRIPTION
**Pull request by asdacap**
Parking ideas....

- An attempt to clearly(?) separate components that use world state.
- There are three main user of state provider, the main block verification, block production and rpcs.
- The state provider is used not only in tx executor, but also in contracts, widthrawal processors and such. The same state provider instance must be shared between all of these components, depending on cases. 
- ReadOnlyTxProcessingEnv exposes its `StateProvider` to other class, which uses it in their constructor which is the reason why this work now. As long as no mistake is done. And you don't mix two of them.
- We could either: 
  - 1. Modify all these components so that they are not constructed with state provider, instead each method invocation take `IWorldState`. I tried this and the amount of change is very significant. Also arguably make things a bit harder to code.
  - 2. Use a dependency injection framework to automatically recreate all these components with the same `IWorldState` whenever we need a world state. This is probably what @smartprogrammer93 suggested, probably. This arguably make evolving the code easier, and probably make things less error prone because if you try to resolve a component that require (directly or indirectly) `IWorldState` without defining a scope, you'd get an error. But still significant amount of work on the plugin side. But once that is done, for each scope just specify the correct state for `IWorldState`, and other code should work magically. It is however, in theory take a bit extra cpu cycle, and somewhat doing things halfway. 
- This is an attempt at no 2. This uses `Autofac` as it has a more robust lifetime management. The container is setup in a new step, `InitializeContainer` which to prevent having to change everything at once, just setup some used component as an instance from `_api`.  Plugins can override registration by implementing `IModule`. 

## Changes

- _List the changes_

#### What types of changes does your code introduce?

- [ ] Bugfix (a non-breaking change that fixes an issue)
- [ ] New feature (a non-breaking change that adds functionality)
- [ ] Breaking change (a change that causes existing functionality not to work as expected)
- [ ] Optimization
- [ ] Refactoring
- [ ] Documentation update
- [ ] Build-related changes
- [ ] Other: _Description_

#### Requires testing

- [ ] Yes
- [ ] No

#### If yes, did you write tests?

- [ ] Yes
- [ ] No

#### Notes on testing

_Optional. Remove if not applicable._

#### Requires documentation update

- [ ] Yes
- [ ] No

_If yes, link the PR to the docs update or the issue with the details labeled `docs`. Remove if not applicable._

#### Requires explanation in Release Notes

- [ ] Yes
- [ ] No

_If yes, fill in the details here. Remove if not applicable._

## Remarks

_Optional. Remove if not applicable._

### CODE REVIEW

**Comment by Scooletz** [comment]
Isn't the delegation to a DI tool a too big hammer to make it work? There are also other options that listed above:

1. an introduction of an ambient context that is accessible via a property of an implementation of `IWorldState` that provides just a wrap around the world state
2. a creation of a higher construct than `IWorldState` that is passed down and called to obtain the state and pass it down whenever possible

**Comment by asdacap** [comment]
It is a big hammer.
1. The problem is defining the "ambient context". 
2. The problem is "passing it down". Its not just the transaction executor, its everything that uses transaction executor or execute before or after it. Or a contract. And not just for mainnet. Does it use the same state?

**Comment by smartprogrammer93** [comment]
The big hammer could be useful for other stuff? Maybe one day we can use it for all dependencies. I have tried an implementation of nethermind API microsoft's DI, but if Autofac has the some extra features we need, why not?

**Comment by Scooletz** [comment]
> The problem is "passing it down". Its not just the transaction executor, its everything that uses transaction executor or execute before or after it. Or a contract. And not just for mainnet. Does it use the same state?

Then on a much much higher level we'd

```csharp

using (worldStateManager.BeingScope(stateRootHash))
{
 // do your work
}
```

I believe there are only a few places that would require such an intervention 👀

**Comment by asdacap** [comment]
Yea, so instead of 

```
using (worldStateManager.BeingScope(stateRootHash))
{
 // do your work
}
```

I'm thinking

```
using (var worldState = worldStateManager.BeingScope(stateRootHash))
{
  var whateverTheThingIs = createTheThing(worldState);
  whateverTheThingIs.DoIt();
}
```

The problem is `createTheThing`. With a DI framework, that is automatic. Without, its not. Its not just mainnet, but also plugins, and also future use case. The whole `ReadOnlyTxProcessingEnv` would not need to exist with a DI framework.

**Comment by Scooletz** [comment]
The ambient context passed in `AsyncLocal<IWorldState>` could solve the creation issue. You'd create things as before and then refer to a stub that delegates to the context. This will have some overhead, but I bet it will be much smaller than the other things like Keccak etc. This would not introduce the big DI and would not require recreation. The penalty to be paid would be the access cost to the async local. This could be ammortized by caching it to a local variable in hot paths.

**Comment by asdacap** [comment]
That is another way, but I feel like that is too implicit and error prone.

**Comment by Scooletz** [comment]
This is implicit and thanks to that, it involves not that many changes. As the entry points are limited, so can be scoping. And the last, but not least, it can nullify the context at the end so no leakage. I'm not pushing for that, rather playing a devil's advocate.

**Pull request closed without merging**
