### PR TITLE
Annotate debug errors

### PR DESCRIPTION
**Pull request by benaadams**
## Changes

- Add `DEBUG/ERROR` to errors output during Debug logging

#### What types of changes does your code introduce?

- [x] Refactoring

#### Requires testing

- [x] No

### CODE REVIEW

**Review by LukaszRozmej — APPROVED** [review]

**Comment by benaadams** [comment]
> Not sure about this approach. Maybe it's better to display log levels for each message? Say, in 3 letter labels like "INF", "WRN", "ERR", "DBG".

You are trying to make @kamilchodola sad 😅

**Comment by benaadams** [comment]
> Not sure about this approach. Maybe it's better to display log levels for each message? Say, in 3 letter labels like "INF", "WRN", "ERR", "DBG".

Is so can log debug to file and filter out these as noise
```
<logger name="*" minlevel="Info" writeTo="auto-colored-console-async">
    <filters>
        <when condition="contains('${message}', 'DEBUG/ERROR')" action="Ignore" />
            <when condition="true" action="Log" />
            </filters>
</logger>
```

Though question might be why do we do mismatched logging?

**Comment by kamilchodola** [comment]
@rubo Case is - it is not actually DBG log - it is an Error which is thrown only if debug logs are enabled. 
So imho - something worth knowing about but not important enough to be a "standard error". 

But what it does to me personally is - i have some scripts which are parsing logs to make sure sync went well and nothing unexpected happened. When I enable debug logging to file only (keeping info to file) I still get some unexpected logs like this to info level and need any way to filter those out to not make my tests fail.

**Comment by LukaszRozmej** [comment]
Yeah it is special diagnostic case, bit of a hack, but whatever.

**Comment by rubo** [comment]
> it is not actually DBG log - it is an Error which is thrown only if debug logs are enabled

Then things are more confusing, if not misleading:

```cs
 if (_logger.IsDebug) _logger.Error()
```

It kinda defeats the purpose of having log levels. I don't have any suggestions at the moment but generally, we need to come up with a better approach. Otherwise, these hacky things tend to replicate themselves here and there.

**Comment by kamilchodola** [comment]
Agree and already was thinking on how to solve that but didn't come with any solution for now.

Reason for this PR was actually that this happened again :D

**Pull request merged**
