### PR TITLE
Add missing peer types to limits

### PR DESCRIPTION
**Pull request by benaadams**
## Changes

- Add missing peer types to limit calcs

#### What types of changes does your code introduce?

- [x] Bugfix (a non-breaking change that fixes an issue)
- [ ] New feature (a non-breaking change that adds functionality)
- [ ] Breaking change (a change that causes existing functionality not to work as expected)
- [ ] Optimization
- [ ] Refactoring
- [ ] Documentation update
- [ ] Build-related changes
- [ ] Other: _Description_

#### Requires testing

- [ ] Yes
- [x] No

#### If yes, did you write tests?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by MarekM25 — APPROVED** [review]
Looks good. Did you check if GethSyncLimits is used by Erigon?

**Comment by benaadams** [comment]
> Did you check if GethSyncLimits is used by Erigon?

Can't see anything particularly suggesting limits, but Geth limits is better than throwing :)

**Comment by benaadams** [comment]
> Reth?

Added

**Comment by MarekM25** [comment]
> > Did you check if GethSyncLimits is used by Erigon?
> 
> Can't see anything particularly suggesting limits, but Geth limits is better than throwing :)

Sure, makes perfect sense ;) And IG Erigon is using the geth limit. We can ask them

**Pull request merged**
