### PR TITLE
Revert "Serialize Json direct to Http PipeWriter" (#6369)

### PR DESCRIPTION
**Pull request by benaadams**
Contributes to #6556

## Changes

- Revert "Serialize Json direct to Http PipeWriter" (#6369)

#### What types of changes does your code introduce?

- [x] Bugfix (a non-breaking change that fixes an issue)

#### Requires testing

- [ ] Yes
- [ ] No

#### If yes, did you write tests?

- [ ] Yes
- [ ] No

### CODE REVIEW

**Review by LukaszRozmej — APPROVED** [review]
Can you elaborate where is the leak?

**Comment by benaadams** [comment]
> Can you elaborate where is the leak?

This isn't the leak we are looking for ; as it's not a leak perse more a very large memory reservation due to the sizes of the Json responses, so it has the memory reasdy for the next very large response. It allocates less per request but hangs onto a lot of memory between requests:

image

**Comment by LukaszRozmej** [comment]
> > Can you elaborate where is the leak?
> 
> This isn't the leak we are looking for ; as it's not a leak perse more a very large memory reservation due to the sizes of the Json responses, so it has the memory reasdy for the next very large response. It allocates less per request but hangs onto a lot of memory between requests:
> 
> image

200MB is not the end of the world if it is pooled memory as you say. Are there any parameters to control it?

**Comment by benaadams** [comment]
Will keep this as is as other source identified

**Pull request closed without merging**
