### PR TITLE
Update rocksdb with the loading order fix

### LINKED ISSUE #6544: Node fails to start with metrics enabled
**Description**
After upgrading to v1.25.0, the node would not start with metrics enabled

**Steps to Reproduce**
1. Upgrade to v1.25.0
2. Start the node with --Metrics.Enabled=true

**Actual behavior**
Node does not start with
```
Jan 15 13:30:29 nethermind[4032754]: Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
Jan 15 13:30:29 nethermind[4032754]:    at RocksDbSharp.Native.MarshalNullTermAsciiStr(IntPtr nullTermStr)
Jan 15 13:30:29 nethermind[4032754]:    at RocksDbSharp.Native.rocksdb_property_value_string(IntPtr db, String propname)
Jan 15 13:30:29 nethermind[4032754]:    at RocksDbSharp.RocksDb.GetProperty(String propertyName)
Jan 15 13:30:29 nethermind[4032754]:    at Nethermind.Db.Rocks.DbOnTheRocks.GetSize() in /home/node/nethermind/src/Nethermind/Nethermind.Db.Rocks/DbOnTheRocks.cs:line 241
Jan 15 13:30:29 nethermind[4032754]:    at Nethermind.Db.KeyValueStoreCompressingExtensions.EOACompressingDb.GetSize() in /home/node/nethermind/src/Nethermind/Nethermind.Db/CompressingDb.cs:line 144
Jan 15 13:30:29 nethermind[4032754]:    at Nethermind.Db.FullPruning.FullPruningDb.GetSize() in /home/node/nethermind/src/Nethermind/Nethermind.Db/FullPruning/FullPruningDb.cs:line 118
Jan 15 13:30:29 nethermind[4032754]:    at Nethermind.Init.Steps.StartMonitoring.<SetupMetrics>b__5_0() in /home/node/nethermind/src/Nethermind/Nethermind.Init/Steps/StartMonitoring.cs:line 94
Jan 15 13:30:29 nethermind[4032754]:    at Nethermind.Monitoring.Metrics.MetricsController.UpdateMetrics(Object state) in /home/node/nethermind/src/Nethermind/Nethermind.Monitoring/Metrics/MetricsController.cs:line 200
Jan 15 13:30:29 nethermind[4032754]:    at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
```

**Expected behavior**
Node should start

**Desktop (please complete the following information):**
Please provide the following information regarding your setup:
 - Operating System: Linux
 - Version: 22.04.3 LTS
 - Installation Method: Github build from source

### PR DESCRIPTION
**Pull request by flcl42**
Fixes #6544 

## Changes

- Update RocksDB with https://github.com/curiosity-ai/rocksdb-sharp/pull/51

#### What types of changes does your code introduce?

- [x] Bugfix (a non-breaking change that fixes an issue)
- [ ] New feature (a non-breaking change that adds functionality)
- [ ] Breaking change (a change that causes existing functionality not to work as expected)
- [ ] Optimization
- [ ] Refactoring
- [ ] Documentation update
- [ ] Build-related changes
- [ ] Other: _Description_

#### Requires testing

- [x] Yes
- [ ] No

#### If yes, did you write tests?

- [ ] Yes
- [x] No

#### Notes on testing

Significant db version change 8.3 -> 8.10

#### Requires explanation in Release Notes

- [ ] Yes
- [ ] No

When building from source or using ppa, the client does not use system-installed version of rocksdb anymore

### CODE REVIEW

**Review by benaadams — APPROVED** [review]
Test is trolling you

```
  Failed Should_have_required_version [110 ms]
  Error Message:
   Expected string to be "8.3.2" with a length of 5, but "8.10.0" has a length of 6, differs near "10."
```

**Review by rubo — APPROVED** [review]
This needs to be tested for sync issues. We have that issue since the v8.6.x.

cc @kamilchodola @asdacap

**Comment by asdacap** [comment]
Not sure how nuget works, but does it already include it?

**Comment by rubo** [comment]
> Not sure how nuget works, but does it already include it?

Yes. It should.

**Comment by asdacap** [comment]
Screenshot_2024-02-19_14-07-06

Definitely higher CPU time per node during sync. Not sure why.

**Comment by asdacap** [comment]
Compaction readahead does not seems to have much of an impact as before.

**Comment by asdacap** [comment]
CompactionReadahead seems to only have significant impact on iops if direct reads is turned on now due to a change in rocksdb https://github.com/facebook/rocksdb/pull/11631/files. This likely depends on the filesystem now.

**Review by asdacap — APPROVED** [review]
Well, I ran out of idea.

**Pull request merged**
