### PR TITLE
CI: Switch Fix chiado test failures and switch action to matrix setup 

### PR DESCRIPTION
**Pull request by brbrr**
## Changes

- Switch CL from `lighthouse:sigp/lighthouse:latest` to `lighthouse` to resolve the sync issue on Chiado net
- Use matrix setup in GH Action to simplify maintainability 

#### What types of changes does your code introduce?

- [ ] Bugfix (a non-breaking change that fixes an issue)
- [ ] New feature (a non-breaking change that adds functionality)
- [ ] Breaking change (a change that causes existing functionality not to work as expected)
- [ ] Optimization
- [ ] Refactoring
- [ ] Documentation update
- [x] Build-related changes
- [ ] Other: _Description_

#### Requires testing

- [ ] Yes
- [x] No

#### If yes, did you write tests?

- [ ] Yes
- [ ] No

### CODE REVIEW

**Review by FalcoXYZ — APPROVED** [review]
Nice use of the matrix. LGTM

**Review by rubo — COMMENTED** [review]
I'd like to reduce the indentation to 2 spaces.

**Comment by brbrr** [comment]
> I'd like to reduce the indentation to 2 spaces.

Yeah, I wasn't happy about the number of whitespace changes, but it seems that it is expected as per `.editorconfig`: https://github.com/NethermindEth/nethermind/blob/master/.editorconfig#L18

**Comment by kamilchodola** [comment]
LGTM
great that you refactored it to matrix :) Applied this approach in other actions but forgot I can make it here as well :)

**Review by kamilchodola — APPROVED** [review]

**Pull request merged**
