### PR TITLE
Increase Eth timeout from 3 to 10 seconds

### PR DESCRIPTION
**Pull request by LukaszRozmej**
## Changes:
Increase timeout for GetHeaders/GetBlock/GetReceipts/GetState to 10s, this helps:
1. When the payload are big and throughput is small
2. When latency gets high

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [x] Other (please describe): 

Increase network timeout

## Testing
**Requires testing**

- [ ] Yes
- [x] No

**In case you checked yes, did you write tests??**

- [ ] Yes
- [ ] No

### CODE REVIEW

**Review by tkstanczak — CHANGES_REQUESTED** [review]
this will break syncs when you are connected to many bad nodes

also I think there is a separate timeout that will fire much before 30 seconds (general message timeout of 5 seconds)

**Comment by LukaszRozmej** [comment]
> this will break syncs when you are connected to many bad nodes
> 
> also I think there is a separate timeout that will fire much before 30 seconds (general message timeout of 5 seconds)

Yes I somewhat agree this might cause some issues where we connect to mostly bad nodes. Geth does calculate this timeout dynamicly per node.

But the current limit is also causing issues in some circumstances. We are giving 3 sec for Block/Receipt/State requests where those things are happening:
1. In PacketSender: serialize message, send the message over the network, the message size can be quite substantial (KB)
2. The other node has to deserialize the message, fetch the requested data from DB, push it through the network
3. The response size can be up to 2 MB

This is all done in parallel so we can be downloading multiple 2MB responses at the same time. Without beefy internet connection it times out often (on my connetion I have issues with goerli even on default timeout).

30s might be overkill but I would consider setting 10s as something reasonable for now.

Also wasn't able to find any general 5s timeout, can you elaborate?

**Comment by LukaszRozmej** [comment]
As 30s can be considered overkill and we might keep bad peers, lets try 10s for now.

**Comment by LukaszRozmej** [comment]
@tkstanczak agreed for the increase

**Pull request merged**
