### PR TITLE
Remove Kiln testnet configs

### PR DESCRIPTION
**Pull request by Zachinquarantine**
## Changes
Removes remaining configs for the deprecated "Kiln" testnet.

## Types of changes
Removes JSON configs and various other configs.
#### What types of changes does your code introduce?

- [ ] Bugfix (a non-breaking change that fixes an issue)
- [ ] New feature (a non-breaking change that adds functionality)
- [ ] Breaking change (a fix or a feature that would cause existing functionality not to work as expected)
- [ ] Documentation update
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional or API changes)
- [ ] Build-related changes
- [ ] Other: _description_ 

#### Requires testing

- [ ] Yes
- [x] No

#### If yes, did you write tests?

- [ ] Yes
- [ ] No

### CODE REVIEW

**Review by MarekM25 — CHANGES_REQUESTED** [review]
I haven't removed it because it was used by Lodestar team in their CI. Let me confirm if they're still using it

**Comment by rubo** [comment]
@MarekM25 Yes, they still have that in their CI. It's worth pinging them for this removal.

**Comment by dapplion** [comment]
CC: @g11tech

**Comment by g11tech** [comment]
> CC: @g11tech, he built that CI you mention on Lodestar

I don't think we use kiln configs but i will check and update what we use

**Comment by MarekM25** [comment]
Yes, I confirmed it with @g11tech before. Thx @Zachinquarantine for your PR :)

**Review by MarekM25 — APPROVED** [review]

**Pull request merged**
