### PR TITLE
Revise the file header notice

### PR DESCRIPTION
**Pull request by rubo**
## Changes
As agreed with our legal department, the file header has been replaced with a more concise and appropriate one.

## Types of changes

What types of changes does your code introduce?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [x] Other (please describe): Replaced the file header

## Testing
**Requires testing**

- [ ] Yes
- [x] No

**In case you checked yes, did you write tests??**

- [ ] Yes
- [x] No

## Further comments (optional)

It is highly recommended to replace the current one with the new one whenever possible. That will lead to less clutter in the files and an overall reduction in repo size.

### CODE REVIEW

**Comment by LukaszRozmej** [comment]
Should we change that in all existing files?

**Comment by rubo** [comment]
@LukaszRozmej We should add this to new files and replace the older header when modifying existing files. Over time, we will have it replaced, or at some point, we can do this for all files in one go.

**Comment by LukaszRozmej** [comment]
We can do it with some command with Visual Studio as far as I remember

**Review by MarekM25 — APPROVED** [review]

**Comment by rubo** [comment]
@LukaszRozmej Just added a new rule to EditorConfig, so the IDE suggests that automatically. I maybe make another PR with all file headers updated.

**Pull request merged**
