### PR TITLE
Kch/improve one click

### PR DESCRIPTION
**Pull request by kamilchodola**
## Changes

- _Use script for waiting + add wait for node to be created + add unique tag in naming to avoid collision in names_

#### What types of changes does your code introduce?

- [X] Bugfix (a non-breaking change that fixes an issue)
- [ ] New feature (a non-breaking change that adds functionality)
- [ ] Breaking change (a change that causes existing functionality not to work as expected)
- [ ] Optimization
- [ ] Refactoring
- [ ] Documentation update
- [ ] Build-related changes
- [ ] Other: _Description_

#### Requires testing

- [X] Yes
- [ ] No

#### If yes, did you write tests?

- [ ] Yes
- [X] No

#### Notes on testing

Tested here: https://github.com/NethermindEth/nethermind/actions/runs/4832100061

### CODE REVIEW

**Review by smartprogrammer93 — CHANGES_REQUESTED** [review]
Can we not use actions on a private repo and bring them over to nethermind repo?

**Comment by smartprogrammer93** [comment]
@kamilchodola I understand, but for security reasons i prefer it is located within the repo.

**Comment by kamilchodola** [comment]
@smartprogrammer93 Ok so I'll move a script also in there to keep it under nethermind control :)

**Review by smartprogrammer93 — APPROVED** [review]

**Comment by kamilchodola** [comment]
Just synced a node with this one - works better, wait for node until created + more proof for the same names of machines (this may corrupt data in Grafana)

**Pull request merged**
