### PR TITLE
Upgrade Microsoft.AspNetCore.DataProtection to 6.0.8

### PR DESCRIPTION
**Pull request by LukaszRozmej**
Closes #4408, #4407, #4406, #4405, #4404

## Changes:
Update package for security reasons

## Types of changes

What types of changes does your code introduce?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [x] Other (please describe): dependency update

## Testing
**Requires testing**

- [x] Yes
- [ ] No

**In case you checked yes, did you write tests??**

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by MarekM25** [comment]
how was it tested?

**Comment by LukaszRozmej** [comment]
`NodeKeyManagerTests ` use `ProtectedPrivateKey` which uses this package on linux

**Comment by LukaszRozmej** [comment]
Posdao test green

**Comment by dceleda** [comment]
Have we run full tests with these changes?
If not then please don't merge.

**Review by flcl42 — APPROVED** [review]

**Review by rubo — APPROVED** [review]

**Comment by LukaszRozmej** [comment]
> Have we run full tests with these changes? If not then please don't merge.

`Full test` is not defined

**Pull request merged**
