### PR TITLE
EvmStack word introduced

### PR DESCRIPTION
**Pull request by Scooletz**
This PR reintroduces `Word` structure that was removed due to an erroneous behavior in https://github.com/NethermindEth/nethermind/pull/2816. The EvmStack is rewritten to use the `Word`. Whether `Uint256` could be used instead, should be discussed before this PR is merged. Possibly, the naming of `ulong` fields should be aligned with `Uint256`.

### Setup 

``` ini
BenchmarkDotNet=v0.12.1, OS=Windows 10.0.18363.1379 (1909/November2018Update/19H2)
Intel Core i7-6700HQ CPU 2.60GHz (Skylake), 1 CPU, 8 logical and 4 physical cores
.NET Core SDK=5.0.103
  [Host]        : .NET Core 5.0.3 (CoreCLR 5.0.321.7212, CoreFX 5.0.321.7212), X64 RyuJIT
  .NET Core 5.0 : .NET Core 5.0.3 (CoreCLR 5.0.321.7212, CoreFX 5.0.321.7212), X64 RyuJIT

Job=.NET Core 5.0  Runtime=.NET Core 5.0  
```

### Before

|   Method |                    v |      Mean |     Error |    StdDev |    Median | Gen 0 | Gen 1 | Gen 2 | Allocated | Code Size |
|--------- |--------------------- |----------:|----------:|----------:|----------:|------:|------:|------:|----------:|----------:|
|     **Byte** |                    **?** | **11.113 ns** | **0.2380 ns** | **0.6752 ns** | **11.001 ns** |     **-** |     **-** |     **-** |         **-** |     **661 B** |
| PushZero |                    ? |  7.802 ns | 0.1644 ns | 0.3167 ns |  7.706 ns |     - |     - |     - |         - |     573 B |
|  PushOne |                    ? |  8.400 ns | 0.2100 ns | 0.5957 ns |  8.221 ns |     - |     - |     - |         - |     577 B |
|     Swap |                    ? | 23.787 ns | 0.5937 ns | 1.7223 ns | 23.275 ns |     - |     - |     - |         - |    1226 B |
|      Dup |                    ? | 12.831 ns | 0.2423 ns | 0.2693 ns | 12.764 ns |     - |     - |     - |         - |    1229 B |
|  **Uint256** |                    **0** | **15.404 ns** | **0.3328 ns** | **0.9549 ns** | **15.232 ns** |     **-** |     **-** |     **-** |         **-** |     **875 B** |
|   Int256 |                    0 | 28.032 ns | 0.5479 ns | 1.0156 ns | 27.713 ns |     - |     - |     - |         - |    1535 B |
|  **Uint256** | **11579(...)39935 [78]** | **16.346 ns** | **0.3488 ns** | **1.0229 ns** | **16.246 ns** |     **-** |     **-** |     **-** |         **-** |     **875 B** |
|   Int256 | 11579(...)39935 [78] | 29.173 ns | 0.6919 ns | 2.0184 ns | 28.504 ns |     - |     - |     - |         - |    1535 B |
|  **Uint256** | **12512(...)57123 [24]** | **14.707 ns** | **0.2842 ns** | **0.2659 ns** | **14.650 ns** |     **-** |     **-** |     **-** |         **-** |     **875 B** |
|   Int256 | 12512(...)57123 [24] | 27.901 ns | 0.5671 ns | 1.1195 ns | 27.590 ns |     - |     - |     - |         - |    1535 B |

### After

|   Method |                    v |      Mean |     Error |    StdDev | Gen 0 | Gen 1 | Gen 2 | Allocated | Code Size |
|--------- |--------------------- |----------:|----------:|----------:|------:|------:|------:|----------:|----------:|
|     **Byte** |                    **?** | **10.409 ns** | **0.1982 ns** | **0.1854 ns** |     **-** |     **-** |     **-** |         **-** |     **649 B** |
| PushZero |                    ? |  7.083 ns | 0.1367 ns | 0.1141 ns |     - |     - |     - |         - |     564 B |
|  PushOne |                    ? |  7.940 ns | 0.1621 ns | 0.1592 ns |     - |     - |     - |         - |     566 B |
|     Swap |                    ? |  9.965 ns | 0.2017 ns | 0.1788 ns |     - |     - |     - |         - |     669 B |
|      Dup |                    ? |  9.376 ns | 0.1249 ns | 0.1107 ns |     - |     - |     - |         - |     745 B |
|  **Uint256** |                    **0** | **13.121 ns** | **0.2702 ns** | **0.3787 ns** |     **-** |     **-** |     **-** |         **-** |     **824 B** |
|   Int256 |                    0 | 26.159 ns | 0.5071 ns | 0.4743 ns |     - |     - |     - |         - |    1484 B |
|  **Uint256** | **11579(...)39935 [78]** | **12.831 ns** | **0.1433 ns** | **0.1593 ns** |     **-** |     **-** |     **-** |         **-** |     **824 B** |
|   Int256 | 11579(...)39935 [78] | 26.490 ns | 0.3960 ns | 0.3704 ns |     - |     - |     - |         - |    1484 B |
|  **Uint256** | **12512(...)57123 [24]** | **13.227 ns** | **0.2746 ns** | **0.4809 ns** |     **-** |     **-** |     **-** |         **-** |     **824 B** |
|   Int256 | 12512(...)57123 [24] | 26.414 ns | 0.3757 ns | 0.3331 ns |     - |     - |     - |         - |    1484 B |

### CODE REVIEW

**Comment by Scooletz** [comment]
@tkstanczak I'm leaving it as a draft for a discussion. It's faster and according to my understanding it should be a safe approach comparing to the previous one. We can discuss it and think whether or not this should be pursued. Being given the previous error, I think before merging it, heavier testing is required.

**Comment by tkstanczak** [comment]
cool thing, I would love to understand where the speed differences are coming from and whether we can remode our Uint256 to be there (maybe we just need to change the alignment of UInt256?)

then we can take UInt256 on / off stack?

**Comment by Scooletz** [comment]
Sure. Let me keep it open @tkstanczak for now and think about possibly removing the `Word`. The gains are visible. It'd be awesome to have it safe, and ultimately, merged 😃

**Comment by Scooletz** [comment]
I think I have a reason why `Word` and `Uint256` should be kept separated. `Uint256` is from a separate library. I think that having Nethermind evm implementation based on the external library offsets is not the best thing to do. Also, after tracking `.PopBytes`, which includes treating them as `Keccak` for `LOG` operations, I think this two should be kept separate, even, if they are aligned with the physical layout @tkstanczak

**Comment by tkstanczak** [comment]
@LukaszRozmej how to best test this? shall we run smoke tests on it?
Would you like to add any extra EVM tests?

**Comment by LukaszRozmej** [comment]
@Scooletz do you know why previous version worked most of the times and failed only seldom?

**Comment by Scooletz** [comment]
@LukaszRozmej I didn't get a repro on a failure. My assumption is that with reading a `Span<byte>` to `Word` with all the `Unsafe.Unaligned` was actually missing some alignment, meaning, that it wasn't properly read. This PR changes the way words are handled. Now, the stack is created from words only which are turned into `Span<byte>` whenever needed. This happens for either reporting the value to a tracer or pushing/popping bytes.

**Comment by tkstanczak** [comment]
@Scooletz can you open a request to merge to a non-master branch on Nethermind?

**Comment by Scooletz** [comment]
I'm not sure I follow @tkstanczak You mean to retarget this PR or to create a separate one with the same changes? 
Is this related to https://github.com/NethermindEth/nethermind/pull/2834 and you created it on your own?

**Comment by Scooletz** [comment]
I have green tests from `Ethereum.Blockchain.Block.Test`. This branch requires some good squashing and a bit more clean up. This will be cleaned up tomorrow. 

FYI @tkstanczak

**Comment by Scooletz** [comment]
This PR is substituted by #2848 , with the reasoning provided in the follow up PR.

**Pull request closed without merging**
