### PR TITLE
Upgrade to RocksDB v9.4.0

### PR DESCRIPTION
**Pull request by rubo**
## Changes

Upgraded RocksDB to v9.4.0.

#### What types of changes does your code introduce?

- [ ] Bugfix (a non-breaking change that fixes an issue)
- [ ] New feature (a non-breaking change that adds functionality)
- [ ] Breaking change (a change that causes existing functionality not to work as expected)
- [ ] Optimization
- [ ] Refactoring
- [ ] Documentation update
- [ ] Build-related changes
- [x] Other: Database upgrade

#### Requires testing

- [x] Yes
- [ ] No

#### If yes, did you write tests?

- [ ] Yes
- [x] No

#### Notes on testing

Needs manual testing

### CODE REVIEW

**Comment by rubo** [comment]
@kamilchodola Could you please compare this to the current one?

**Comment by kamilchodola** [comment]
For future there is nice action which can compare it quite easily (create two equals envs for two nodes and spawn some rpc load tests to see any difference and then can be verified on Grafana)
https://github.com/NethermindEth/nethermind/actions/runs/10194669630

HOPE IT STILL WORKS :)

**Review by LukaszRozmej — APPROVED** [review]

**Comment by LukaszRozmej** [comment]
@kamilchodola can we merge it?

**Review by benaadams — APPROVED** [review]

**Comment by kamilchodola** [comment]
I did not had any objections merging it last time, everything looked like working smoothly. We could merge it and keep an eye on that while testing other things.

**Review by kamilchodola — APPROVED** [review]

**Pull request merged**
