### PR TITLE
FEAT: Add utilization monitor script 

### PR DESCRIPTION
**Pull request by HarshCasper**
## Changes:

Add a script to monitor:

- CPU Utilization
- RAM Utilization
- Memory 

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Other (please describe): 

## Testing
**Requires testing**

- [X] Yes
- [ ] No

**In case you checked yes, did you write tests??**

- [ ] Yes
- [X] No

## Further comments (optional)

This PR has been created after a discussion with @1swaraj and @matilote to run on a cron job. Further improvements would be made as comments are made on the PR.

### CODE REVIEW

**Review by 1swaraj — CHANGES_REQUESTED** [review]
Why is this in Golang and not Bash ?

**Comment by HarshCasper** [comment]
> Why is this in Golang and not Bash ?

My presumption was that we need to have it in Golang. I can convert it to BASH if you would like.

**Comment by HarshCasper** [comment]
Hi @1swaraj 

I had a talk with @matilote and he suggested migrating this in BASH. I will promptly do so.

**Comment by HarshCasper** [comment]
Hi @1swaraj 

Can you please have a look again and let me know any further things that needs to be changed/added?

**Comment by HarshCasper** [comment]
Hi @1swaraj @matilote 👋 

Can you please have a look at this?

**Comment by matilote** [comment]
> Hi @1swaraj @matilote 👋
> 
> Can you please have a look at this?

It needs to run on Windows and macOS as well.

image

**Comment by HarshCasper** [comment]
> > Hi @1swaraj @matilote 👋
> > Can you please have a look at this?
> 
> It needs to run on Windows and macOS as well.
> 
> image

I'm looking into it, then.

**Review by 1swaraj — CHANGES_REQUESTED** [review]
Are you going to create separate scripts for windows & mac ?

**Pull request closed without merging**
