### PR TITLE
403 error code on authentication error

### PR DESCRIPTION
**Pull request by deffrian**
Fixes | Closes | Resolves #

> Anything marked as optional that you didn't need to fill in, please remove it from the PR description. Choose one of the keywords above to refer to the issue this PR solves, followed by the issue number (e.g Fixes # 666). If there is no issue, remove the line. Remove this note after reading.

## Changes:
- Send 403 Forbidden error code on authentication error

## Types of changes

What types of changes does your code introduce?
_Put an `x` in the boxes that apply_

- [ x ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Other (please describe): 

## Testing
**Requires testing**

- [ ] Yes
- [ x ] No

### CODE REVIEW

**Review by MarekM25 — CHANGES_REQUESTED** [review]
please add PR description. 

Are we not following the spec now?
How it works on version 1.14.0?
What issues we could have because of that?

**Comment by deffrian** [comment]
1. The spec doesn't say anything about this.
403 error code used for auth errors [link](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/403)
Currently, geth sends 403 when message is not authenticated.
2. We send 200OK when message is NOT authenticated.
3. Now it's hard to understand when request is successfully executed. You have to parse body, but it should be clear from HTTP hedaer

**Comment by MarekM25** [comment]
How did you test it?

**Comment by deffrian** [comment]
`curl --data '{"jsonrpc":"2.0","method":"eth_syncing", "params":[], "id":3}' -H "Content-Type: application/json" -H "Authorization: <invalid_token>" localhost:8551 -v`

**Comment by MarekM25** [comment]
> `curl --data '{"jsonrpc":"2.0","method":"eth_syncing", "params":[], "id":3}' -H "Content-Type: application/json" -H "Authorization: <invalid_token>" localhost:8551 -v`

It doesn't sound like enough testing. You should run CL & run hive tests (engine-auth)

**Comment by deffrian** [comment]
> > `curl --data '{"jsonrpc":"2.0","method":"eth_syncing", "params":[], "id":3}' -H "Content-Type: application/json" -H "Authorization: <invalid_token>" localhost:8551 -v`
> 
> It doesn't sound like enough testing. You should run CL & run hive tests (engine-auth)

Done, lighthouse and hive tests work fine

**Review by MarekM25 — APPROVED** [review]

**Pull request merged**
