### PR TITLE
TxPool account cache

### PR DESCRIPTION
**Pull request by benaadams**
## Changes

- Intra block account cache for txPool

image

#### What types of changes does your code introduce?

- [ ] Bugfix (a non-breaking change that fixes an issue)
- [ ] New feature (a non-breaking change that adds functionality)
- [ ] Breaking change (a change that causes existing functionality not to work as expected)
- [x] Optimization
- [ ] Refactoring
- [ ] Documentation update
- [ ] Build-related changes
- [ ] Other: _Description_

#### Requires testing

- [ ] Yes
- [x] No

#### If yes, did you write tests?

- [x] Yes
- [ ] No

### CODE REVIEW

**Comment by LukaszRozmej** [comment]
Cache with single digit hit rate? Probably not worth it?

**Comment by benaadams** [comment]
> Cache with single digit hit rate? Probably not worth it?

Surges to 10%+ peridoically

image

Is 70% of tx filtering; so cache covers about 7% of tx filtering?

image

**Comment by benaadams** [comment]
> Still kind of ouch, either we need consider increasing it or having more clever way of keeping values (hit count?)

Ideally would keep the cache between blocks and update the accounts as they are set at the end of block and share between txn pool and blocks (as hot accounts in txPool are likely to be used next by the blocks)

But that's more complicated

Atm it ditches the cache on each new block

**Comment by benaadams** [comment]
> Still kind of ouch, either we need consider increasing it or having more clever way of keeping values (hit count?)

Increasing the cache to 4096 and carrying it across blocks increases the hit rate very significantly; however then need to keep it up to date rather than have it working on stale data (after the first add to cache)

image

**Pull request closed without merging**
