### PR TITLE
Use blob gas instead of count

### PR DESCRIPTION
**Pull request by flcl42**
All blob calculations should use blob gas and do not rely on max blob count to be consistent

## Changes

- Use blob gas instead of count

#### What types of changes does your code introduce?

- [x] Bugfix (a non-breaking change that fixes an issue)
- [ ] New feature (a non-breaking change that adds functionality)
- [ ] Breaking change (a change that causes existing functionality not to work as expected)
- [ ] Optimization
- [ ] Refactoring
- [ ] Documentation update
- [ ] Build-related changes
- [ ] Other: _Description_

#### Requires testing

- [x] Yes
- [ ] No

#### If yes, did you write tests?

- [x] Yes
- [ ] No

### CODE REVIEW

**Review by LukaszRozmej — COMMENTED** [review]
I don't like it, makes it less clear. Why the change?

**Comment by flcl42** [comment]
> I don't like it, makes it less clear. Why the change?

1. The spec mentions gas only, not blob count
2. It's better to maintain only one type of limit, and as we decided to parametrise max blob gas per block, let's stick to it

**Comment by marcindsobczak** [comment]
> > I don't like it, makes it less clear. Why the change?
> 
> 1. The spec mentions gas only, not blob count
> 2. It's better to maintain only one type of limit, and as we decided to parametrise max blob gas per block, let's stick to it

But `MaxBlobGasPerBlock` is set as `MaxBlobGasPerBlock = GasPerBlob * MaxBlobsPerBlock` so in case of future changes we would only need to change `MaxBlobsPerBlock`. IMO this change is decreasing readability of the code and I don't like it (I'm the person who introduced `MaxBlobsPerBlock`), but it is a minor implementation detail so if you have a big preference to go this way, I don't mind

**Review by marcindsobczak — APPROVED** [review]

**Comment by flcl42** [comment]
> I don't like it, makes it less clear. Why the change?

The current reason is that blob count did not reflect custom settings for gnosis which led to a block production issue

**Review by LukaszRozmej — APPROVED** [review]

**Review by marcindsobczak — APPROVED** [review]

**Review by LukaszRozmej — APPROVED** [review]

**Pull request merged**
