### PR TITLE
Rename: `ValidatorPublicKey` -> `ValidatorPubKey`

### PR DESCRIPTION
**Pull request by rjnrohit**
## Changes
Align WithdrawalRequestV1 with EIP-7002: https://github.com/ethereum/execution-apis/pull/549

#### What types of changes does your code introduce?

- [ ] Bugfix (a non-breaking change that fixes an issue)
- [ ] New feature (a non-breaking change that adds functionality)
- [ ] Breaking change (a change that causes existing functionality not to work as expected)
- [ ] Optimization
- [x] Refactoring
- [ ] Documentation update
- [ ] Build-related changes

#### Requires testing

- [ ] Yes
- [x] No

#### If yes, did you write tests?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by benaadams — APPROVED** [review]

**Comment by LukaszRozmej** [comment]
Can you provide description for the PR to know why this is being changed?

**Comment by rjnrohit** [comment]
> Can you provide description for the PR to know why this is being changed?

Added

**Comment by LukaszRozmej** [comment]
Shouldn't it be `ValidatorPubkey`?

**Comment by rjnrohit** [comment]
> Shouldn't it be `ValidatorPubkey`?

Yes, you are correct. updated, thanks!

**Review by LukaszRozmej — APPROVED** [review]

**Pull request merged**
