### PR TITLE
Logs cpu info on start

### PR DESCRIPTION
**Pull request by asdacap**
- Logs cpu info on start. 
- Makes debugging easier.
- Using another MIT licensed library as it claims to works on all platform. 
- Looks like this:

Screenshot from 2022-12-15 14-09-56

## Changes:
- Logs cpu info on start

## Types of changes

What types of changes does your code introduce?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Other (please describe): 

## Testing
**Requires testing**

- [X] Yes
- [ ] No

**In case you checked yes, did you write tests??**

- [ ] Yes
- [X] No: Only logs. 

**Comments about testing , should you have some** (optional)

## Further comments (optional)

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by LukaszRozmej** [comment]
Can we make it more concise, interesting part from example would be:
`CPU: AMD Ryzen 7950X, 16C32T`

maybe also on same line `Clocks: 5269-5881MHz`
maybe also on same line supported instructions we are into so: `SSE (max supported version), AVX (max supported version)`

**Comment by asdacap** [comment]
Ok, I'll keep the name, the number of core (the VM can change them) and combine the clocks. Flags are much harder to decipher, I'd rather just print them and figureout what they mean when needed.

**Comment by LukaszRozmej** [comment]
> Ok, I'll keep the name, the number of core (the VM can change them) and combine the clocks. Flags are much harder to decipher, I'd rather just print them and figureout what they mean when needed.

I get what you are saying but we have enough wall of text on startup, adding 1 line is fine but adding so many - is pushing it.

**Review by LukaszRozmej — APPROVED** [review]

**Comment by kamilchodola** [comment]
@LukaszRozmej @asdacap 
Just FYI
Used this library also in tests to report CPU +RAM into Notion, and noticed it fails to retrieve RAM data from Ubuntu machine. It works well for Windows, but for Ubuntu it did not find any RAMSticks (tested on Linode machines).

**Pull request merged**
