### PR TITLE
Avoid interface calls for Logging checks

### PR DESCRIPTION
**Pull request by benaadams**
## Changes

- Wrap `ILogger` in an `Logger` struct that when created sets values in struct for `IsTrace`, `IsDebug`, `IsInfo`, `IsWarn`, `IsError` so the guards are a fast check inline against the struct rather than being an interface call each time.
- Make the logger cache `static`

#### What types of changes does your code introduce?

- [x] Optimization

#### Requires testing

- [x] No

### CODE REVIEW

**Review by LukaszRozmej — COMMENTED** [review]
So the only potential downside I see is that we theoretically could change logging rules during runtime and I think NLog would cope with that, here we fix the rules on startup and we won't have that feature. In practice we don't really use it. How much gain is this by itself?
Would love to hear more opinions before deciding.

**Comment by benaadams** [comment]
> So the only potential downside I see is that we theoretically could change logging rules during runtime and I think NLog would cope with that, here we fix the rules on startup and we won't have that feature. In practice we don't really use it. How much gain is this by itself? Would love to hear more opinions before deciding.

You did already decide that 3 years ago 😉https://github.com/NethermindEth/nethermind/blob/807b87cefa3993a96fc6c2ea0bd02d9c2198303e/src/Nethermind/Nethermind.Logging.NLog/NLogLogger.cs#L30-L37

It just on the otherside of the interface call 😢

**Review by LukaszRozmej — APPROVED** [review]
Can we make it less disruptive than 326 files changed?

**Comment by benaadams** [comment]
> Can we make it less disruptive than 326 files changed?

Renamed the struct to `ILogger` 🤢 99 files

**Pull request merged**
