### PR TITLE
Adds failing test for un-assigned storage values.

### PR DESCRIPTION
**Pull request by MicahZoltu**
Fixing this test will bring Nethermind in line with OpenEthereum and Geth.

### CODE REVIEW

**Comment by MicahZoltu** [comment]
Note: This test is *expected* to fail at the moment as it is meant to model what Nethermind *should* do rather than what it *actually* does.

Note 2: I drafted this PR in GitHub web interface, so it may not even compile.  I'll try to monitor CI to see if that is the case and fix it as necessary.

**Comment by MicahZoltu** [comment]
Do these checks actually run?

**Comment by tkstanczak** [comment]
> Do these CI checks actually run?

Normally they do when there is a code change from someone from the team. Maybe it is some kind of protection against others invoking the processing.

**Comment by tkstanczak** [comment]
@MicahZoltu this does not make sense - the test - 41 zeros here do not make sense
What value does OE return? This is meant to be usable for proof regeneration and storage values are stored truncated and the storage proofs contain leaf node RLP (serialized trie nodes) and not the storage values.
So, at the moment it is a bit confusing. Can investigate further but would need to launch OE and Geth.

**Comment by MicahZoltu** [comment]
Closing in favor of #1991.

**Pull request closed without merging**
