### PR TITLE
Remove .DS_Store files and Improve README.md

### PR DESCRIPTION
**Pull request by AlexSSD7**
* Remove *not gitignored* .DS_Store files (macOS directory indexes).
* Update Ubuntu installations instruction (tested on 20.04)
* Shortened macOS installation command (`brew install ...`)
* Other README fixes

### CODE REVIEW

**Comment by AlexSSD7** [comment]
I will also add tutorials for other distros.

**Comment by tkstanczak** [comment]
@AlexSSD7 I will merge after resolving conflicts, I will try to resolve

**Comment by AlexSSD7** [comment]
Please do not merge as I'm working on adding tutorials for a variety of distros (including FreeBSD)

**Comment by AlexSSD7** [comment]
Update on FreeBSD: It seems like Microsoft provides neither precompiled binaries nor installation instructions for .NET SDK.

**Pull request merged**
