### PR TITLE
Partially fix hive test

### PR DESCRIPTION
**Pull request by asdacap**
## Changes:
- Connect invalid block chain ahead of time.
- Refactored unit test so that all test uses Context.

## Types of changes

What types of changes does your code introduce?
_Put an `x` in the boxes that apply_

- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Other (please describe): 

## Testing
**Requires testing**

- [X] Yes
- [ ] No

**In case you checked yes, did you write tests??**

- [ ] Yes
- [X] No

**Comments about testing , should you have some** (optional)

- Can sync goerli to head.
- Hive test when run locally have no regression.
- Still running hive test on github action....

## Further comments (optional)

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by MarekM25** [comment]
Which hive tests are partially fixed thanks to this PR? 
Do you think we can add some unit tests?

**Comment by asdacap** [comment]
I think it was one of the `GasUsed` tests. Don't remember exactly the case.

**Comment by asdacap** [comment]
Ok, now I remember I think. We don't do any validation in beacon header sync, so no chain is connected here. But during MergeBlockDownloader, a block failed, which mean it stop suggesting at that point, invalid chain is not connected to its descendent as no validation was attempted. Then another NP of it's descendent also fail block validation, but since its not connected, it's last valid block is its not-validated header instead of the first non-valid block.

**Comment by MarekM25** [comment]
> Ok, now I remember I think. We don't do any validation in beacon header sync, so no chain is connected here. But during MergeBlockDownloader, a block failed, which mean it stop suggesting at that point, invalid chain is not connected to its descendent as no validation was attempted. Then another NP of it's descendent also fail block validation, but since its not connected, it's last valid block is its not-validated parent block instead of the parent of the first non-valid block.

Ok, I think I understood issue, but what will happen if we restart client in this case?

**Comment by asdacap** [comment]
I'm guessing, we will have the same issue.

**Comment by MarekM25** [comment]
> I'm guessing, we will have the same issue.

ok, so this PR will improve our behaviour, but do you have any thoughts what we can do after restart?

**Comment by asdacap** [comment]
Not at the moment

**Pull request merged**
