### PR TITLE
Rebase the `develop` branch onto `master`

### PR DESCRIPTION
**Pull request by rubo**
Rebased the `develop` branch onto `master`.

### CODE REVIEW

**Comment by smartprogrammer93** [comment]
There are still conflicts :'(

**Comment by rubo** [comment]
@smartprogrammer93 Yes, this should be force-pushed like the previous one but should keep all the changes.

**Review by smartprogrammer93 — APPROVED** [review]
Looks like it has all the changes

**Comment by LukaszRozmej** [comment]
Close?

**Pull request closed without merging**
