### PR TITLE
Move to System.Text.Json for Serialization 

### PR DESCRIPTION
**Pull request by benaadams**
## Changes

- Move to System.Text.Json for Serialization 

#### What types of changes does your code introduce?

- [ ] Bugfix (a non-breaking change that fixes an issue)
- [ ] New feature (a non-breaking change that adds functionality)
- [ ] Breaking change (a change that causes existing functionality not to work as expected)
- [x] Optimization
- [ ] Refactoring
- [ ] Documentation update
- [ ] Build-related changes
- [ ] Other: _Description_

#### Requires testing

- [ ] Yes
- [x] No

#### If yes, did you write tests?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by LukaszRozmej** [comment]
Can we completely remove Newtonsoft from everywhere?

**Comment by benaadams** [comment]
> Can we completely remove Newtonsoft from everywhere?

Yes; and is complicated for deserialization* so will just do this PR as is and follow up with that

*both due to different shapes of `JsonRpcRequest` data and modular dispatch registratration

**Comment by LukaszRozmej** [comment]
You can probably integrate #4414 for Abi parsing

**Comment by LukaszRozmej** [comment]
I would still insist to do it all in one and remove all Newtonsoft-related stuff from code:
1. While the main reason for the change is performance, leaving 2 json libraries in makes the code a mess and hard to reason about. Also harder to maintain.
2. When we remove all Newtonsoft dependencies we will better understand all the scenarios that we need to handle.
3. This will lead to easier review and testing.

I know it is not the most interesting thing to do.

**Comment by benaadams** [comment]
> I would still insist to do it all in one and remove all Newtonsoft-related stuff 

Down to 20 compile errors :)

**Pull request closed without merging**
