### PR TITLE
Move SyncStatusList to ConcurrentCollections

### PR DESCRIPTION
**Pull request by LukaszRozmej**
## Changes

- Move SyncStatusList to ConcurrentCollections
- Track gaps only
- Don't allocate large array
- Don't do full locks

#### What types of changes does your code introduce?

- [ ] Bugfix (a non-breaking change that fixes an issue)
- [ ] New feature (a non-breaking change that adds functionality)
- [ ] Breaking change (a change that causes existing functionality not to work as expected)
- [x] Optimization
- [ ] Refactoring
- [ ] Documentation update
- [ ] Build-related changes
- [ ] Other: _Description_

#### Requires testing

- [x] Yes
- [ ] No

#### If yes, did you write tests?

- [ ] Yes
- [x] Not yet

### CODE REVIEW

**Review by benaadams — CHANGES_REQUESTED** [review]
Looks good; only issue is concurrent decrement of `LowestInsertWithoutGaps` from two methods

**Comment by LukaszRozmej** [comment]
> Looks good; only issue is concurrent decrement of `LowestInsertWithoutGaps` from two methods

but `_insertedItems` should have unique items, so this shouldn't happen in practice due to the if-check.

**Review by benaadams — APPROVED** [review]

**Comment by LukaszRozmej** [comment]
Some stats before->after:

total throughput 583.08bps -> 598.33bps
time 2:45 -> 2:30

it hanged in the end so has bugs, not worth it?

**Comment by benaadams** [comment]
Let's take a boring approach https://github.com/NethermindEth/nethermind/pull/5642

**Pull request closed without merging**
