### PR TITLE
Remove mining methods

### LINKED ISSUE #5949: Remove mining from eth_ namespace
https://github.com/ethereum/execution-apis/pull/430

### PR DESCRIPTION
**Pull request by bitcoinbrisbane**
Resolves #5949

_Please choose one of the keywords above to refer to the issue this PR solves followed by the issue number (e.g. Fixes #000). If no issue number, remove the line. Also, remove everything marked optional that is not applicable. Remove this note after reading._

## Changes

- Remove mining methods

#### What types of changes does your code introduce?

- [ ] Bugfix (a non-breaking change that fixes an issue)
- [ ] New feature (a non-breaking change that adds functionality)
- [ ] Breaking change (a change that causes existing functionality not to work as expected)
- [ ] Optimization
- [ ] Refactoring
- [ ] Documentation update
- [ ] Build-related changes
- [ ] Other: _Description_

#### Requires testing

- [ ] Yes
- [ ] No

#### If yes, did you write tests?

- [ ] Yes
- [ ] No

#### Notes on testing

_Optional. Remove if not applicable._

#### Requires documentation update

- [ ] Yes
- [ ] No

_If yes, link the PR to the docs update or the issue with the details labeled `docs`. Remove if not applicable._

#### Requires explanation in Release Notes

- [ ] Yes
- [ ] No

_If yes, fill in the details here. Remove if not applicable._

## Remarks

_Optional. Remove if not applicable._

### CODE REVIEW

**Comment by MarekM25** [comment]
Thx for your contribution, but it looks like solution is not building:
`/home/runner/work/nethermind/nethermind/src/Nethermind/Nethermind.JsonRpc.Test/JsonRpcServiceTests.cs(157,26): error CS1061: 'IEthRpcModule' does not contain a definition for 'eth_getWork' and no accessible extension method 'eth_getWork' accepting a first argument of type 'IEthRpcModule' could be found (are you missing a using directive or an assembly reference?) [/home/runner/work/nethermind/nethermind/src/Nethermind/Nethermind.JsonRpc.Test/Nethermind.JsonRpc.Test.csproj]`

**Comment by bitcoinbrisbane** [comment]
> Thx for your contribution, but it looks like solution is not building: `/home/runner/work/nethermind/nethermind/src/Nethermind/Nethermind.JsonRpc.Test/JsonRpcServiceTests.cs(157,26): error CS1061: 'IEthRpcModule' does not contain a definition for 'eth_getWork' and no accessible extension method 'eth_getWork' accepting a first argument of type 'IEthRpcModule' could be found (are you missing a using directive or an assembly reference?) [/home/runner/work/nethermind/nethermind/src/Nethermind/Nethermind.JsonRpc.Test/Nethermind.JsonRpc.Test.csproj]`

I fixed all those interface methods.  Let me see if i pushed.

**Comment by bitcoinbrisbane** [comment]
> Thx for your contribution, but it looks like solution is not building:
> `/home/runner/work/nethermind/nethermind/src/Nethermind/Nethermind.JsonRpc.Test/JsonRpcServiceTests.cs(157,26): error CS1061: 'IEthRpcModule' does not contain a definition for 'eth_getWork' and no accessible extension method 'eth_getWork' accepting a first argument of type 'IEthRpcModule' could be found (are you missing a using directive or an assembly reference?) [/home/runner/work/nethermind/nethermind/src/Nethermind/Nethermind.JsonRpc.Test/Nethermind.JsonRpc.Test.csproj]`

dotnet build in the JSONRpc project is working for me.  Let me work it out

image

**Review by MarekM25 — APPROVED** [review]

**Comment by MarekM25** [comment]
LGTM @bitcoinbrisbane! Could I mark it as ready for review?

**Comment by bitcoinbrisbane** [comment]
> LGTM @bitcoinbrisbane! Could I mark it as ready for review?

Sure!  I wanted to update the PR Readme, but if you think its good :)

**Pull request merged**
