### PR TITLE
Adjust snap request threshold

### PR DESCRIPTION
**Pull request by asdacap**
- Adjust some request threshold for snap request queuing.
- Reduces the amount no request to dispatch during snap sync, but sync time too inconsistent to know for sure if it affect anything.
- Increase storage queue size before skipping account range request.
- Check for high code queue first before dequeing not full storage queue.

Screenshot from 2023-06-20 19-14-34

## Changes

- Slight refactor.
- Adjust threshold.

#### What types of changes does your code introduce?

- [X] Optimization
- [X] Refactoring

#### Requires testing

- [X] Yes
- [ ] No

#### If yes, did you write tests?

- [X] Yes
- [ ] No

#### Notes on testing

- Definitely can sync.

### CODE REVIEW

**Comment by benaadams** [comment]
Might want to also change this as I think only Geth currently supports Snap; rather than "not Nethermind"?

https://github.com/NethermindEth/nethermind/blob/03e25c3c38a4e8db33e13a8e7c935fa5a5d91df7/src/Nethermind/Nethermind.Synchronization/Peers/SyncPeerExtensions.cs#L32-L37

**Review by benaadams — APPROVED** [review]

**Comment by benaadams** [comment]
Code formatting :P

**Comment by asdacap** [comment]
> Might want to also change this as I think only Geth currently supports Snap; rather than "not Nethermind"?
> 
> https://github.com/NethermindEth/nethermind/blob/03e25c3c38a4e8db33e13a8e7c935fa5a5d91df7/src/Nethermind/Nethermind.Synchronization/Peers/SyncPeerExtensions.cs#L32-L37

I think we should remove this completely actually.

**Comment by LukaszRozmej** [comment]
> > Might want to also change this as I think only Geth currently supports Snap; rather than "not Nethermind"?
> > https://github.com/NethermindEth/nethermind/blob/03e25c3c38a4e8db33e13a8e7c935fa5a5d91df7/src/Nethermind/Nethermind.Synchronization/Peers/SyncPeerExtensions.cs#L32-L37
> 
> I think we should remove this completely actually.

The idea there was that Nethermind will advertise snap sync protocol when it is syncing, but we don't want to actually sync from Nethermind as it won't serve any data. This is a temporary thing until we implement snap server. Not sure if Besu has similar issue.

**Comment by asdacap** [comment]
Well, yea. But if we do try to sync from nethermind, it will disconnect us, leaving some space for geth peer.

**Pull request merged**
