### PR TITLE
Use ready to run

### PR DESCRIPTION
**Pull request by benaadams**
## Changes

- Start with optimized code (may make exe size a lot larger)

#### What types of changes does your code introduce?

- [ ] Bugfix (a non-breaking change that fixes an issue)
- [ ] New feature (a non-breaking change that adds functionality)
- [ ] Breaking change (a change that causes existing functionality not to work as expected)
- [x] Optimization
- [ ] Refactoring
- [ ] Documentation update
- [ ] Build-related changes
- [ ] Other: _Description_

#### Requires testing

- [ ] Yes
- [x] No

#### If yes, did you write tests?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by LukaszRozmej — COMMENTED** [review]
Can you post some results here?

**Comment by LukaszRozmej** [comment]
Does it messes up with redistributables in any way (probably not as because of native libraries we already have them per os-arch)

**Comment by benaadams** [comment]
> Does it messes up with redistributables in any way (probably not as because of native libraries we already have them per os-arch)

Nah, that's when you get more exotic and start using `<PublishTrimmed>` then things start to go wrong

**Comment by benaadams** [comment]
> Can you post some results here?

Adds 25MB to the packages; in exchange for pre-optimized binaries (they will still reoptimize later with PGO), but they don't need a slow running warmup Jit phase

image
image

**Comment by LukaszRozmej** [comment]
> > Can you post some results here?
> 
> Adds 25MB to the packages and 10 mins to the publish time; in exchange for pre-optimized binaries (they will still reoptimize later with PGO), but they don't need a slow running warmup Jit phase
> 
> image image

And what is the startup time benefit?

**Review by LukaszRozmej — APPROVED** [review]
Approving, but lets wait for more people taking a look.

**Review by asdacap — APPROVED** [review]
Looks interesting.

**Comment by benaadams** [comment]
> And what is the startup time benefit?

Start-up is ok as Nethermind isn't a serverless app that starts on demand; however blockprocessing won't move to an optimised version for a while after startup and have been complaints that it it too slow at start but then gets faster and then is fine. So should address that to an extent

**Comment by rubo** [comment]
Kinda controversial. Do we have any _notable_ performance improvement?

**Pull request merged**
