### PR TITLE
Refactor product versioning and revise Docker files

### PR DESCRIPTION
**Pull request by rubo**
Refactors product versioning and fixes that for Docker images.

**IMPORTANT!** With this change, before branching a new release from the `master` branch, the product version must be bumped up in `Directory.Build.props`. The release Git tag must always match the version defined in `Directory.Build.props`.

## Changes:
- The product version is now hardcoded in [`Directory.Build.props`](https://github.com/NethermindEth/nethermind/blob/master/src/Nethermind/Directory.Build.props)
- GitHub Actions and Docker files have been updated in accordance with the abovementioned change

## Types of changes

What types of changes does your code introduce?

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality not to work as expected)
- [ ] Documentation Update
- [ ] Code style update (formatting, renaming)
- [x] Refactoring (no functional changes, no api changes)
- [x] Build related changes
- [ ] Other (please describe): 

## Testing
**Requires testing**

- [x] Yes
- [ ] No

**In case you checked yes, did you write tests??**

- [ ] Yes
- [x] No

The following scripts have been tested:

- `build-nethermind-docker-images.yml`
- `build-nethtest-hive-docker-images.yml`
- `run-nethermind-tests.yml`

### CODE REVIEW

**Review by MarekM25 — APPROVED** [review]
I talked with @rubo and I'm okay with the change. However, I haven't verified the script, so let's wait for @FalcoXYZ review.

**Comment by FalcoXYZ** [comment]
@rubo did you test these changes?

**Comment by rubo** [comment]
@rubo Yes, I've tested but I modified them before testing to prevent publishing a new release here and there. If you're okay with the changes, I'll test it again but the full test will occur on the actual release.

**Comment by FalcoXYZ** [comment]
Please test it locally (**and confirm here it works**) and add back everything that you removed for testing. I will review once you add it all back.

**Comment by rubo** [comment]
Whoops! 😄 Sorry, refresh the page.

**Comment by FalcoXYZ** [comment]
I've checked the Github Actions and Dockerfile, looks OK. I'm not familiar with the actual dotnet stuff so can't comment on that. 
Good job on removing the "set-output" and changing it, as that will be deprecated soon.

**Review by FalcoXYZ — APPROVED** [review]

**Pull request merged**
