### PR TITLE
Remove Data Marketplace

### PR DESCRIPTION
**Pull request by rubo**
Nethermind Data Marketplace (NDM) solution has been moved to the new [data-marketplace](https://github.com/NethermindEth/data-marketplace) repo.

## Changes:
The following has been removed:
- `NDM.sln`
- All `Nethermind.DataMarketplace*` projects
- `Nethermind.RocksDbExtractor` project

## Types of changes

What types of changes does your code introduce?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [x] Other (please describe): Removed irrelevant stuff

## Testing
**Requires testing**

- [ ] Yes
- [x] No

**In case you checked yes, did you write tests??**

- [ ] Yes
- [x] No

## Further comments (optional)

The NDM solution references the projects in this repo. That reference is now broken. As the solution is abandoned, I see no reason to waste a time on fixing that as it may break again at any moment in the future.

### CODE REVIEW

**Review by asdacap — APPROVED** [review]

**Comment by LukaszRozmej** [comment]
Do any pipelines need changing? Shall we move any of the issues to separate repository? Looks like most if not all of them are closed https://github.com/NethermindEth/nethermind/issues?q=is%3Aissue+is%3Aopen+ndm+label%3Andm

**Review by LukaszRozmej — APPROVED** [review]

**Comment by rubo** [comment]
@LukaszRozmej No GitHub Actions workflow refers to NDM. They look good.

@smartprogrammer93 @marcindsobczak We have a lot of references to NDM in our docs. I think those should be removed as well.

**Comment by rubo** [comment]
@LukaszRozmej Could you please review these and decide whether we should leave them intact, remove, or modify:

- [InitializeBlockchain.cs:267](https://github.com/NethermindEth/nethermind/blob/feature/remove-data-marketplace/src/Nethermind/Nethermind.Init/Steps/InitializeBlockchain.cs#L267)
- [AddCapabilityMessageSerializer.cs](https://github.com/NethermindEth/nethermind/blob/feature/remove-data-marketplace/src/Nethermind/Nethermind.Network/P2P/Messages/AddCapabilityMessageSerializer.cs#L10)
- [TestBuilder.cs:27](https://github.com/NethermindEth/nethermind/blob/feature/remove-data-marketplace/src/Nethermind/Nethermind.Overseer.Test/Framework/TestBuilder.cs#L27)
- [Nethermind.Runner/configs/ndm_*](https://github.com/NethermindEth/nethermind/tree/feature/remove-data-marketplace/src/Nethermind/Nethermind.Runner/configs)

**Comment by LukaszRozmej** [comment]
> @LukaszRozmej Could you please review these and decide whether we should leave them intact, remove, or modify:
> 
> * [InitializeBlockchain.cs:267](https://github.com/NethermindEth/nethermind/blob/feature/remove-data-marketplace/src/Nethermind/Nethermind.Init/Steps/InitializeBlockchain.cs#L267)
> * [AddCapabilityMessageSerializer.cs](https://github.com/NethermindEth/nethermind/blob/feature/remove-data-marketplace/src/Nethermind/Nethermind.Network/P2P/Messages/AddCapabilityMessageSerializer.cs#L10)
> * [TestBuilder.cs:27](https://github.com/NethermindEth/nethermind/blob/feature/remove-data-marketplace/src/Nethermind/Nethermind.Overseer.Test/Framework/TestBuilder.cs#L27)
> * [Nethermind.Runner/configs/ndm_*](https://github.com/NethermindEth/nethermind/tree/feature/remove-data-marketplace/src/Nethermind/Nethermind.Runner/configs)

1. Needed in subscription factory - we can remove comment.
2. Maybe we should remove everything regarding `AddCapability` message, can be done in another PR.
3. I see this used in other contexts, probably incorrect message. You can investigate.
4. Will delete in other PR

**Pull request merged**
