### PR TITLE
Remove `v` of non-legacy tx signature from RPC response

### PR DESCRIPTION
**Pull request by rubo**
## Changes

Removed the `v` component of the non-legacy transaction signatures from the RPC response.

#### What types of changes does your code introduce?

- [x] Bugfix (a non-breaking change that fixes an issue)
- [ ] New feature (a non-breaking change that adds functionality)
- [ ] Breaking change (a change that causes existing functionality not to work as expected)
- [ ] Optimization
- [ ] Refactoring
- [ ] Documentation update
- [ ] Build-related changes
- [ ] Other: _Description_

#### Requires testing

- [x] Yes
- [ ] No

#### If yes, did you write tests?

- [x] Yes
- [ ] No

#### Notes on testing

Also, needs manual testing.

#### Requires documentation update

- [ ] Yes
- [x] No

#### Requires explanation in Release Notes

- [ ] Yes
- [x] No

## Remarks

This fix should address the Nethermind's part of [the issue](https://github.com/ethers-io/ethers.js/issues/3835) with ethers v6.

### CODE REVIEW

**Review by LukaszRozmej — APPROVED** [review]
Looks good, but can you explain the reasoning?

**Comment by rubo** [comment]
> Looks good, but can you explain the reasoning?

@LukaszRozmej Please see the remarks

**Comment by benaadams** [comment]
> This fix should address the Nethermind's part of https://github.com/ethers-io/ethers.js/issues/3835 with ethers v6.

Since causes issue in major 3rd party lib should this be a candidate for pulling into 1.20.0?

@MarekM25 @kamilchodola

**Comment by rubo** [comment]
Note that this PR alone won't address ethers' issue as it doesn't handle `yParity` in hex.

**Pull request merged**
