### PR TITLE
Removing totalDifficulty field from BlockForRpc class while returning…

### LINKED ISSUE #7397: Remove totalDifficulty from block in json reponse
based on this merged PR:
https://github.com/ethereum/execution-apis/pull/570

### PR DESCRIPTION
**Pull request by shubham-sonthalia**
Resolves #7397 

_Please choose one of the keywords above to refer to the issue this PR solves followed by the issue number (e.g. Fixes #000). If no issue number, remove the line. Also, remove everything marked optional that is not applicable. Remove this note after reading._

## Changes

- Removes totalDifficulty field from `BlockForRpc` class 
- Removes the property from the expected response.

#### What types of changes does your code introduce?

- [ ] Bugfix (a non-breaking change that fixes an issue)
- [x] New feature (a non-breaking change that adds functionality)
- [ ] Breaking change (a change that causes existing functionality not to work as expected)
- [ ] Optimization
- [ ] Refactoring
- [ ] Documentation update
- [ ] Build-related changes
- [ ] Other: _Description_

#### Requires testing

- [] Yes
- [ ] No

#### If yes, did you write tests?

- [ ] Yes
- [ ] No

#### Notes on testing

_Optional. Remove if not applicable._

#### Requires documentation update

- [ ] Yes
- [ ] No

_If yes, link the PR to the docs update or the issue with the details labeled `docs`. Remove if not applicable._

#### Requires explanation in Release Notes

- [ ] Yes
- [ ] No

### CODE REVIEW

**Comment by shubham-sonthalia** [comment]
@smartprogrammer93 could you suggest if these changes are in the right direction?

**Comment by smartprogrammer93** [comment]
@shubham-sonthalia looks like it is.

**Comment by smartprogrammer93** [comment]
Keep you PR in Draft mode until it is ready for review please 🙏

**Comment by shubham-sonthalia** [comment]
Does the scope of the issue involve removing `totalDifficulty` from the entire solution? Or only for the scope of Rpc modules?

**Comment by smartprogrammer93** [comment]
@shubham-sonthalia only RPC for now

**Comment by shubham-sonthalia** [comment]
I have removed all occurences of `totalDifficulty` in Nethermind.JsonRpc module as well as test files - 

image

I also ran all the tests for the RPC related modules. They are all passing - 

image


I think all changes for the scope of the issue is done. Please let me know your thoughts.

**Comment by LukaszRozmej** [comment]
https://github.com/NethermindEth/nethermind/issues/7397#issuecomment-2352138435

**Review by MarekM25 — APPROVED** [review]
Because total difficulty is not needed in some cases, we can use BlockTreeLookupOptions.TotalDifficultyNotNeeded. For example, if we are reading a block by its hash and do not require TD, we can avoid reading from the blockInfo database.

**Comment by MarekM25** [comment]
> Because total difficulty is not needed in some cases, we can use BlockTreeLookupOptions.TotalDifficultyNotNeeded. For example, if we are reading a block by its hash and do not require TD, we can avoid reading from the blockInfo database.

**Comment by MarekM25** [comment]
> [#7397 (comment)](https://github.com/NethermindEth/nethermind/issues/7397#issuecomment-2352138435)

Yes, it would be good to confirm with blockscout team. On the other hand, not sure if it is used at all for various chains (besides block explorers)

**Comment by LukaszRozmej** [comment]
To be honest I wouldn't merge that PR. Just because Main Ethereum doesn't need it, doesn't mean we should remove it because our clients are using other consensus algorithms and may still need it. Just let it be until proven unnecessary.

**Comment by shubham-sonthalia** [comment]
@LukaszRozmej @smartprogrammer93 Shall I close this PR?

**Comment by smartprogrammer93** [comment]
@shubham-sonthalia, unfortunately, i agree with lukasz as his point makes sense. So we need to close this for now.

**Pull request closed without merging**
