### PR TITLE
Perf/reduce bodies and receipt batch size

### PR DESCRIPTION
**Pull request by asdacap**
- So besu does not have/respect the 2MB message size soft limit, so during old bodies, besu will send bodies message of size 20MB. The problem with this is that 20MB is harder for dotnetty to pool than the usuall 3MB causing slightly higher allocation rate.

- Pending testing... but I recall its something.. not much, but something...

## Changes

- _List the changes_

#### What types of changes does your code introduce?

- [ ] Bugfix (a non-breaking change that fixes an issue)
- [ ] New feature (a non-breaking change that adds functionality)
- [ ] Breaking change (a change that causes existing functionality not to work as expected)
- [ ] Optimization
- [ ] Refactoring
- [ ] Documentation update
- [ ] Build-related changes
- [ ] Other: _Description_

#### Requires testing

- [ ] Yes
- [ ] No

#### If yes, did you write tests?

- [ ] Yes
- [ ] No

#### Notes on testing

_Optional. Remove if not applicable._

#### Requires documentation update

- [ ] Yes
- [ ] No

_If yes, link the PR to the docs update or the issue with the details labeled `docs`. Remove if not applicable._

#### Requires explanation in Release Notes

- [ ] Yes
- [ ] No

_If yes, fill in the details here. Remove if not applicable._

## Remarks

_Optional. Remove if not applicable._

### CODE REVIEW

**Comment by benaadams** [comment]
>   ----> System.Configuration.ConfigurationErrorsException : Config is not correctly formed JSon. See inner exception for details.
  ----> Newtonsoft.Json.JsonReaderException : After parsing a value an unexpected character was encountered: ". Path 'Sync.FastSyncCatchUpHeightDelta', line 22, position 4.

**Review by LukaszRozmej — COMMENTED** [review]
So we have classes like `BeSuSuncLimits` and `GethSyncLimits` ect. 
We also have `Nethermind.Synchronization.Blocks.PeerInfoExtensions` to map to those sync limits.
It looks like those limits are used in `BlockDownloader` but not in `SyncFeeds`.
Maybe we should use it there too?

**Comment by asdacap** [comment]
Those limits are too high. Also, for this purpose it changes depending on the network as some network have smaller blocks. Maybe it should auto adjust depending on tx count instead?

**Comment by asdacap** [comment]
So it turns out, if you only connect to besu, and have another change that prevents them from timing out by autoadjusting request size based on latency, it can indeed explode in memory usage.

(before, after, before, after, before, after, before, after, before, after)
Screenshot_2023-08-09_16-34-14

**Pull request closed without merging**
