### PR TITLE
Add gnosis config

### PR DESCRIPTION
**Pull request by jmederosalvarado**
## Changes:
- Renames xdai chainspec to gnosis
- Adds new config `gnosis`

## Types of changes

What types of changes does your code introduce?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [x] Other (please describe): Config

### CODE REVIEW

**Review by LukaszRozmej — COMMENTED** [review]
Question - Could renaming changespec (instead of having a clone), cause issues when upgrading existing nodes?

**Comment by jmederosalvarado** [comment]
> 

I tested it, at least with a simple setup using `--config xdai` it is not an issue, I think probably because of chainspec as embedded resource

**Comment by LukaszRozmej** [comment]
> > Question - Could renaming changespec (instead of having a clone), cause issues when upgrading existing nodes?
> 
> I tested it, at least with a simple setup using `--config xdai` it is not an issue, I think probably because of chainspec as embedded resource

Yes with embedded one no issue, with custom one there could be an issue. Can we leave xdai chainspec to be more compatible for now?

**Comment by rubo** [comment]
Are all those configs actually used? If some aren't, let's remove those. Not sure about the rest but the `ndm_*` stuff looks obsolete.

**Comment by LukaszRozmej** [comment]
I think `ndm*`, `_mev`, `_validator` configs can be safely removed

**Review by LukaszRozmej — APPROVED** [review]

**Pull request merged**
