### PR TITLE
Eof/valdiation fixes

### PR DESCRIPTION
**Pull request by shemnon**
## Changes

Fixes several small EOF validation testing failures

* Types of changes
* Don't allow out of order subcontainer header
* Require full length data header except in EOFCREATE usage.
* Don't allow repeat header sections
* Reject containers with excess data
* Check container sizes
* Require code sections to end with terminal operator
* Prohibit STATICALL in EOF container code

#### What types of changes does your code introduce?

- [X] Bugfix (a non-breaking change that fixes an issue)
- [ ] New feature (a non-breaking change that adds functionality)
- [ ] Breaking change (a change that causes existing functionality not to work as expected)
- [ ] Optimization
- [ ] Refactoring
- [ ] Documentation update
- [ ] Build-related changes
- [ ] Other: _Description_

#### Requires testing

- [X] Yes
- [ ] No

#### If yes, did you write tests?

- [ ] Yes
- [X] No

#### Notes on testing

Testing is handled by Ethereum Execution Specification Tests, which are in an external repo.

### CODE REVIEW

**Comment by shemnon** [comment]
@benaadams

**Comment by shemnon** [comment]
At least two (large) issues remain:

* Validating subcontainers, but in context of how they are used (EOFCREATE reference containers are Initcode, RETURNCONTRACT are runtime, rather than index based)
* Detecting jumps into immediate data

**Review by benaadams — APPROVED** [review]

**Comment by benaadams** [comment]
@shemnon after updating tests on `feature/evm/eof` branch to v1.0.9 nothing fails in this area; is that failure in our testing progress or tests not yet merged?

**Comment by shemnon** [comment]
I'm using raw EEST fills, there are tests that are not yet in the released.  I'll update my eof test tracker today and have it ready before start of europe business.

**Comment by benaadams** [comment]
> I'm using raw EEST fills, there are tests that are not yet in the released. I'll update my eof test tracker today and have it ready before start of europe business.

I'll wait on merge of this one then, to merge the new tests to the base branch to make sure we are picking up the failures

**Comment by shemnon** [comment]
The automated EOF tests are not being asserted.

https://github.com/NethermindEth/nethermind/blob/970a4f3905e63c973e9ae4b3a38b872a7daba799/src/Nethermind/Ethereum.Blockchain.Pyspec.Test/PragueEofTests.cs#L16

Should be
```
    public void Test(EofTest test) => Assert.That(RunTest(test));
```

**Comment by shemnon** [comment]
[Fixtures for EEST main](https://drive.google.com/file/d/1vk0HQ-S2V2-gK__xhnaa1tWI5Hm4YFtJ/view?usp=drive_link) as of 2024-09-09
Note however, 72 of 76 failing tests are part of fixtures v1.0.9

**Comment by benaadams** [comment]
> The automated EOF tests are not being asserted.

Ah ha, good spot!

Thank you very much for your contribution @shemnon

**Pull request merged**
