### PR TITLE
simplified locks

### PR DESCRIPTION
**Pull request by Scooletz**
A speculative continuation of #7733. Commits:

1. ed403a7 - simplifies the API a bit
2. 15d2b0e - bucket lock, distributing synchronized work over N fixed buckets

### CODE REVIEW

**Comment by benaadams** [comment]
Syncing ran for over 5 hours, restarted job

**Comment by benaadams** [comment]
```
Failed RecreateAccountStateFromOneRangeWithExistenceProof [1 ms]
  Error Message:
   System.IndexOutOfRangeException : Index was outside the bounds of the array.
```

**Comment by LukaszRozmej** [comment]
I'm not confident this is better than original, closing for now

**Comment by damian-orzechowski** [comment]
There were 2 bugs there - one with index needed to be converted to unsigned to avoid `IndexOutOfRangeException` as pointed by @benaadams. 2nd with deadlocking, but I think that was due to unit test construct only.

**Comment by Scooletz** [comment]
This should have been marked as WIP and was the background for the discussion. Chill out 😅

**Comment by LukaszRozmej** [comment]
> This should have been marked as WIP and was the background for the discussion. Chill out 😅

way simpler: https://github.com/NethermindEth/nethermind/pull/7733/commits/0460606be0b4f69e8baa9b91cc8ba6fe44c77a3b

**Pull request closed without merging**
