### PR TITLE
Add zero reward post-merge

### LINKED ISSUE #4616: trace_block no longer returns miner records
The same behaviour happens on Erigon (please see this issue: https://github.com/ledgerwatch/erigon/issues/5462).

While it is true that the miner no longer receives a reward for mining the block, the`eth_getBlockByNumber` routine continues to return a `miner` field. (In the case illustrated in the referenced issue, "miner": "0x57865ba267d48671a41431f471933aec32a7c7d1").

For our application, we use `trace_block` to find "every appearance of every address anywhere on the chain". By removing the miner from `trace_block` post-merge, the node now requires that we call the RPC twice for each block. Once (against `trace_block`) for all the `regular` address and once (against `eth_getBlockByNumber`) for the `miner`. This doubles our processing time when indexing the entire chain.

### PR DESCRIPTION
**Pull request by deffrian**
Fixes | Closes | Resolves #

## Changes:
- Introduces MergeRpcRewardCalculator, same as MergeRewardCalculator, but returns zero reward post-merge instead of no reward
- Duplicated function removed
- PoSSwitcher moved from AuraApi to NethermindApi
- Resolves #4616 

## Types of changes

What types of changes does your code introduce?
_Put an `x` in the boxes that apply_

- [ x ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Other (please describe): 

## Testing
**Requires testing**

- [ ] Yes
- [ x ] No

**In case you checked yes, did you write tests??**

- [ x ] Yes
- [ ] No

### CODE REVIEW

**Comment by LukaszRozmej** [comment]
Can you explain the context of this change? Why is it needed? Why 0-value reward is better here than lack of rewards?

I find this change potentially conflicting with:https://github.com/NethermindEth/nethermind/pull/5005/commits/74616028e000a53363fc4fa7d8aaf6acecb41205
which is needed to support viviani testnet

**Comment by MarekM25** [comment]
@deffrian you should link GitHub issue in PR description :)

**Review by LukaszRozmej — CHANGES_REQUESTED** [review]
So basically adding zero rewards like that can accidentally trigger EIP-155, which is not good and cause consensus issue. We can add this reward here and then filter it out in the actual Reward process if needed in `ApplyMinerReward` (or not calling it at all).

But overall I am not sure if we should add those artificial rewards to tracers at all. Now we are tracing something that isn't actually happening.

**Comment by MarekM25** [comment]
> So basically adding zero rewards like that can accidentally trigger EIP-155, which is not good and cause consensus issue. We can add this reward here and then filter it out in the actual Reward process if needed in `ApplyMinerReward` (or not calling it at all).
> 
> But overall I am not sure if we should add those artificial rewards to tracers at all. Now we are tracing something that isn't actually happening.

I second that! It should be only reported to traces for RPC not changing the consensus logic

**Review by MarekM25 — CHANGES_REQUESTED** [review]
You shouldn't change consensus rules

**Review by LukaszRozmej — APPROVED** [review]

**Pull request merged**
