### PR TITLE
Compressing db

### PR DESCRIPTION
**Pull request by Scooletz**
This PR introduces a notion of a `compressing db` that can wrap a `IDb`  that stores RLPs and optimizes some of the frequently used values with some form of a compression. The compression **should lower the amount of data written to Rocks Db for EOA accounts** as they usually don't have storage set and never have code associated with them. 

This change is backward compatible as no account RLP will have an RLP starting with `0`. The preamble of `0` is used as a discriminator to differentiate between the values stored in raw (regular RLP) or values stored in a compressed form. Once deployed though, it changes the structure of newly written entries applying the compression onto them.

The values is compressed away is based on the suffix of RLP of EOAs.

## Results

The state DB is at 155GB which is ~10GB then the best estimate for the state.

image

## Changes

- `CompressingDb` introduced with covarage of 100%
- `FullPruningDb` wraps its internal RocksDb with `CompressingDb`

#### What types of changes does your code introduce?

- [ ] Bugfix (a non-breaking change that fixes an issue)
- [x] New feature (a non-breaking change that adds functionality)
- [ ] Breaking change (a change that causes existing functionality not to work as expected)
- [x] Optimization
- [ ] Refactoring
- [ ] Documentation update
- [ ] Build-related changes
- [ ] Other: _Description_

#### Requires testing

- [x] Yes
- [ ] No

#### If yes, did you write tests?

- [x] Yes
- [ ] No

#### Notes on testing

Requires synchronizing node from point 0 to prove that is saves a lot.

## Remarks

_Optional. Remove if not applicable._

### CODE REVIEW

**Review by benaadams — APPROVED** [review]
Looks good👍

If just looking at `Account`s could simplify a little if willing to catch less.

Since [`eip-161`](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-161.md) (in 2016?) accounts with storage but without code can no longer be created; and I assume a high percentage of accounts with code have storage?

So if mostly looking at EOA; then they will always end with the same 66 bytes:
```cs
private static ReadOnlySpan<byte> EmptyCodeHashStorageRoot => new byte[]
{
    160,
    86, 232, 31, 23, 27, 204, 85, 166, 255, 131, 69, 230, 146, 192, 248, 110, 91, 72, 224, 27, 153, 108, 173, 192, 1, 98, 47, 181, 227, 99, 180, 33,
    160,
    197, 210, 70, 1, 134, 247, 35, 60, 146, 126, 125, 178, 220, 199, 3, 192, 229, 0, 182, 83, 202, 130, 39, 59, 123, 250, 216, 4, 93, 133, 164, 112
};
```
So on write could simplify the check to 
```cs
var shouldCompress = span.EndsWith(EmptyCodeHashStorageRoot);
```
With the compression being to write the null flag (as now); and truncate the last 66 bytes off; without needing to store any extra length data? (That may make up for less accounts matching with either/or but not both)

**Comment by Scooletz** [comment]
@benaadams This is really cool. I was thinking about library contracts, that might have code but no storage, but there should be only a few of them. I'll make it EOA specific like you proposed.

**Comment by benaadams** [comment]
> and we should be just fine with having a single `0` as the marker atm.

Maybe `0x00_00` just in case there is another format, which could then go to `0x00_01`? 🤔

**Comment by Scooletz** [comment]
@benaadams `0x00` is already composable but is not evolvable. Let's make it evolvable adding the version byte. One more commit then :-)

**Comment by Scooletz** [comment]
I confirmed the sync. The gains are the same (the state db reduced by 6%) with much smaller code change and less performance impacting decoding (one copy, or one search).

**Pull request merged**
