### PR TITLE
Fix `TxDecoder` registration

### PR DESCRIPTION
**Pull request by emlautarom1**
Proper fix instead of #7496

## Changes

- Prefer manual registration
- Remove fishy public constructor
- Add tests for proper registration

#### What types of changes does your code introduce?

- [x] Bugfix (a non-breaking change that fixes an issue)
- [ ] New feature (a non-breaking change that adds functionality)
- [ ] Breaking change (a change that causes existing functionality not to work as expected)
- [ ] Optimization
- [ ] Refactoring
- [ ] Documentation update
- [ ] Build-related changes
- [ ] Other: _Description_

#### Requires testing

- [x] Yes
- [ ] No

#### If yes, did you write tests?

- [x] Yes
- [ ] No

#### Notes on testing

Added tests to ensure that we're using a single `TxDecoder` global instance.

#### Requires documentation update

- [ ] Yes
- [x] No

#### Requires explanation in Release Notes

- [ ] Yes
- [x] No

## Remarks

Registration of these global instances is tricky and very error prone. In an ideal world we would use DI to handle these kind of issues. Let's remember this issue next time DI comes into discussion.

### CODE REVIEW

**Review by LukaszRozmej — APPROVED** [review]

**Review by benaadams — APPROVED** [review]

**Comment by benaadams** [comment]
Neither version registers early enough for a node restart
```
27 Sep 01:02:46 | Step InitializeBlockTree      failed after 21ms Nethermind.Serialization.Rlp.RlpException: Unknown transaction type DepositTx
   at Nethermind.Serialization.Rlp.TxDecoder`1.GetDecoder(TxType txType) in D:\GitHub\nethermind\src\Nethermind\Nethermind.Serialization.Rlp\TxDecoder.cs:line 83
   at Nethermind.Serialization.Rlp.TxDecoder`1.Decode(ValueDecoderContext& decoderContext, T& transaction, RlpBehaviors rlpBehaviors) in D:\GitHub\nethermind\src\Nethermind\Nethermind.Serialization.Rlp\TxDecoder.cs:line 127
   at Nethermind.Serialization.Rlp.TxDecoder`1.Decode(ValueDecoderContext& decoderContext, RlpBehaviors rlpBehaviors) in D:\GitHub\nethermind\src\Nethermind\Nethermind.Serialization.Rlp\TxDecoder.cs:line 90
   at Nethermind.Serialization.Rlp.Rlp.Decode[T](ValueDecoderContext& decoderContext, RlpBehaviors rlpBehaviors) in D:\GitHub\nethermind\src\Nethermind\Nethermind.Serialization.Rlp\Rlp.cs:line 270
   at Nethermind.Serialization.Rlp.BlockDecoder.Decode(ValueDecoderContext& decoderContext, RlpBehaviors rlpBehaviors) in D:\GitHub\nethermind\src\Nethermind\Nethermind.Serialization.Rlp\BlockDecoder.cs:line 247
   at Nethermind.Serialization.Rlp.KeyValueStoreRlpExtensions.Get[TCacheKey,TItem](IReadOnlyKeyValueStore db, TCacheKey cacheKey, ReadOnlySpan`1 key, IRlpStreamDecoder`1 decoder, ClockCache`2 cache, RlpBehaviors rlpBehaviors, Boolean shouldCache) in D:\GitHub\nethermind\src\Nethermind\Nethermind.Serialization.Rlp\KeyValueStoreRlpExtensions.cs:line 66
   at Nethermind.Serialization.Rlp.KeyValueStoreRlpExtensions.Get[TItem](IReadOnlyKeyValueStore db, Int64 blockNumber, ValueHash256 hash, IRlpStreamDecoder`1 decoder, ClockCache`2 cache, RlpBehaviors rlpBehaviors, Boolean shouldCache) in D:\GitHub\nethermind\src\Nethermind\Nethermind.Serialization.Rlp\KeyValueStoreRlpExtensions.cs:line 22
   at Nethermind.Blockchain.Blocks.BlockStore.Get(Int64 blockNumber, Hash256 blockHash, RlpBehaviors rlpBehaviors, Boolean shouldCache) in D:\GitHub\nethermind\src\Nethermind\Nethermind.Blockchain\Blocks\BlockStore.cs:line 89
   at Nethermind.Blockchain.BlockTree.FindBlock(Hash256 blockHash, BlockTreeLookupOptions options, Nullable`1 blockNumber) in D:\GitHub\nethermind\src\Nethermind\Nethermind.Blockchain\BlockTree.cs:line 1289
   at Nethermind.Blockchain.BlockTree.FindBlock(Int64 blockNumber, BlockTreeLookupOptions options) in D:\GitHub\nethermind\src\Nethermind\Nethermind.Blockchain\BlockTree.cs:line 678
   at Nethermind.Blockchain.BlockTree.LoadStartBlock() in D:\GitHub\nethermind\src\Nethermind\Nethermind.Blockchain\BlockTree.Initializer.cs:line 345
   at Nethermind.Blockchain.BlockTree..ctor(IBlockStore blockStore, IHeaderStore headerDb, IDb blockInfoDb, IDb metadataDb, IBlockStore badBlockStore, IChainLevelInfoRepository chainLevelInfoRepository, ISpecProvider specProvider, IBloomStorage bloomStorage, ISyncConfig syncConfig, ILogManager logManager) in D:\GitHub\nethermind\src\Nethermind\Nethermind.Blockchain\BlockTree.cs:line 158
   at Nethermind.Init.Steps.InitializeBlockTree.Execute(CancellationToken cancellationToken) in D:\GitHub\nethermind\src\Nethermind\Nethermind.Init\Steps\InitializeBlockTree.cs:line 57
   at Nethermind.Init.Steps.EthereumStepsManager.ExecuteStep(IStep step, StepInfo stepInfo, CancellationToken cancellationToken) in D:\GitHub\nethermind\src\Nethermind\Nethermind.Init\Steps\EthereumStepsManager.cs:line 153
   at Nethermind.Init.Steps.EthereumStepsManager.ReviewFailedAndThrow() in D:\GitHub\nethermind\src\Nethermind\Nethermind.Init\Steps\EthereumStepsManager.cs:line 211
   at Nethermind.Init.Steps.EthereumStepsManager.InitializeAll(CancellationToken cancellationToken) in D:\GitHub\nethermind\src\Nethermind\Nethermind.Init\Steps\EthereumStepsManager.cs:line 95
   at Nethermind.Runner.Ethereum.EthereumRunner.Start(CancellationToken cancellationToken) in D:\GitHub\nethermind\src\Nethermind\Nethermind.Runner\Ethereum\EthereumRunner.cs:line 36
   at Nethermind.Runner.Program.<>c__DisplayClass8_0.<<Run>b__1>d.MoveNext() in D:\GitHub\nethermind\src\Nethermind\Nethermind.Runner\Program.cs:line 205
```

**Comment by benaadams** [comment]
Runs the saved blocks before the plugins initialize

**Comment by LukaszRozmej** [comment]
> Runs the saved blocks before the plugins initialize

Oh that sounds problematic

**Comment by LukaszRozmej** [comment]
I think I found the fix

**Comment by brbrr** [comment]
to be clear, is this a fix for Optimism specifically?

**Comment by benaadams** [comment]
> to be clear, is this a fix for Optimism specifically?

Yes

**Comment by benaadams** [comment]
> I think I found the fix, was about DepositTx and not TxDecoder in general.

Still errors on start; different error though :)
```
Step InitRlp                  failed after 5ms System.ArgumentNullException: Value cannot be null. (Parameter 'api.TxValidator')
   at System.ArgumentNullException.Throw(String paramName)
   at System.ArgumentNullException.ThrowIfNull(Object argument, String paramName)
   at Nethermind.Api.NethermindApiExtensions.RegisterTxType(INethermindApi api, TxType type, ITxDecoder decoder, ITxValidator validator) in D:\GitHub\nethermind\src\Nethermind\Nethermind.Api\INethermindApi.cs:line 28
   at Nethermind.Optimism.OptimismPlugin.InitRlpDecoders(INethermindApi api) in D:\GitHub\nethermind\src\Nethermind\Nethermind.Optimism\OptimismPlugin.cs:line 83
   at Nethermind.Init.Steps.InitRlp.Execute(CancellationToken _) in D:\GitHub\nethermind\src\Nethermind\Nethermind.Init\Steps\InitRlp.cs:line 37
   at Nethermind.Init.Steps.EthereumStepsManager.ExecuteStep(IStep step, StepInfo stepInfo, CancellationToken cancellationToken) in D:\GitHub\nethermind\src\Nethermind\Nethermind.Init\Steps\EthereumStepsManager.cs:line 153
   at Nethermind.Init.Steps.EthereumStepsManager.ReviewFailedAndThrow() in D:\GitHub\nethermind\src\Nethermind\Nethermind.Init\Steps\EthereumStepsManager.cs:line 211
   at Nethermind.Init.Steps.EthereumStepsManager.InitializeAll(CancellationToken cancellationToken) in D:\GitHub\nethermind\src\Nethermind\Nethermind.Init\Steps\EthereumStepsManager.cs:line 95
   at Nethermind.Runner.Ethereum.EthereumRunner.Start(CancellationToken cancellationToken) in D:\GitHub\nethermind\src\Nethermind\Nethermind.Runner\Ethereum\EthereumRunner.cs:line 36
   at Nethermind.Runner.Program.<>c__DisplayClass8_0.<<Run>b__1>d.MoveNext() in D:\GitHub\nethermind\src\Nethermind\Nethermind.Runner\Program.cs:line 205
```

**Review by benaadams — APPROVED** [review]
Works now

**Comment by LukaszRozmej** [comment]
> Works now

First try!

**Comment by emlautarom1** [comment]
So, to recap, the required changes outside `TxDecoder` were
- Register Optimism `TxType` earlier
- Construct `TxValidator` earlier

**Pull request merged**
