### PR TITLE
Upgrade to RocksDB v7

### LINKED ISSUE #4885: [RocksDB] Check downgrade possibilities of Nethermind whenever RocksDb is upgraded
**Describe the bug**
As per this article:
https://github.com/facebook/rocksdb/wiki/RocksDB-Compatibility-Between-Different-Releases
RocksDB should be able to be downgraded without any issue if no major settings are being changed between versions.

We are planning to upgrade RocksDB to latest version but before that we need to check if this downgrade option can be used by us to prevent any major problems with this.

### PR DESCRIPTION
**Pull request by smartprogrammer93**
Closes #4885

## Changes:
- Bumped Nuget package version to 7.6.0
- Ran Forward and Backward compatibility tests. no issues.
- Still need to benchmark

Any advice would be appreciated @rubo 

## Types of changes

What types of changes does your code introduce?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Other (please describe): 

## Testing
**Requires testing**

- [x] Yes
- [ ] No

**In case you checked yes, did you write tests??**

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by rubo — CHANGES_REQUESTED** [review]
- Tests should be updated as well in [RocksDbTests.cs](https://github.com/NethermindEth/nethermind/blob/feature/rocksdb_version_7.6.0/src/Nethermind/Nethermind.Db.Test/RocksDbTests.cs)
- As RocksDB v7.7 is a few months old, we better use that instead. I see no reason not to do so.

**Comment by rubo** [comment]
@FalcoXYZ We need to test this on arm64 machines.

**Comment by kamilchodola** [comment]
@rubo 
Will put it on my list - I can sync that on 
1. Windows Server 2019 - I had issues with RocksDb6.X (unable to sync any chain) so it is nice test
2. Arm64 - only testnets or partial sync mainnet
3. Mac M1 - only testnets or partial sync mainnet

**Comment by smartprogrammer93** [comment]
Forward compatibility for version 7.7.3 tested and works well after downgrading.

**Comment by rubo** [comment]
Closing in favor of #5065

**Pull request closed without merging**
