### PR TITLE
fix to CancellationTokenSource has been disposed.

### LINKED ISSUE #5021: [Gnosis] "Allocations upgrade failure" during State sync appeard
**Describe the bug**
During sync procedure of gnosis-lighthouse I've noticed for very first time such exception:
image
As @smartprogrammer93 this is something minor but would like to analyze this and check if this may have any side-effect on sync.

I've Never saw that log in past

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Chain: Gnosis + LH
 - Version: 15.0 RC
 
https://seq.nethermind.io/#/events?filter=Contains(NodeName,%20'Smoke-Tests-prerelease-150-resyncs-gnosis-lighthouse')&from=2022-12-16T07:00:00.000Z

### PR DESCRIPTION
**Pull request by smartprogrammer93**
Fixes #5021

The issue seems to be a very rare race condition. either we should lock or try catch and ignore the exception.

## Changes

- locks the cancellationTokenSource before cancellation or disposing.

#### What types of changes does your code introduce?

- [x] Bugfix (a non-breaking change that fixes an issue)
- [ ] New feature (a non-breaking change that adds functionality)
- [ ] Breaking change (a fix or a feature that would cause existing functionality not to work as expected)
- [ ] Documentation update
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional or API changes)
- [ ] Build-related changes
- [ ] Other: _description_ 

#### Requires testing

- [ ] Yes
- [x] No

#### If yes, did you write tests?

- [ ] Yes
- [x] No

#### Notes on testing
its almost impossible to simulate this situation

### CODE REVIEW

**Comment by benaadams** [comment]
`Cancel` is atomic with `IsCancellationRequested` and `Dispose` can be called multiple times, could you check that rather than `_isDisposed` and call cancel in `Dispose` to ensure ordering?

```cs
public void Cancel()
{
    if (!Cancellation.IsCancellationRequested)
    {
        Cancellation.Cancel();
    }
}

public void Dispose()
{
    if (!Cancellation.IsCancellationRequested)
    {
        Cancellation.Cancel();
    }

    Cancellation.Dispose();
}
```

**Comment by benaadams** [comment]
> `Cancel` is atomic with `IsCancellationRequested` and `Dispose` can be called multiple times, could you check that rather than `_isDisposed` and call cancel in `Dispose` to ensure ordering?
> 

Could still slip in there, though less frequently 🤔 Maybe would need to catch; though can drop the `_isDisposed` field

```cs
public void Cancel()
{
    try
    {
        if (Cancellation.IsCancellationRequested)
        {
            Cancellation.Cancel();
        }
    }
    catch (ObjectDisposedException)
    { 
        // If Disposed has been cancelled
    }
}

public void Dispose()
{
    if (Cancellation.IsCancellationRequested)
    {
        Cancellation.Cancel();
    }

    Cancellation.Dispose();
}
```

**Comment by benaadams** [comment]
> > `Cancel` is atomic with `IsCancellationRequested` and `Dispose` can be called multiple times, could you check that rather than `_isDisposed` and call cancel in `Dispose` to ensure ordering?
> 
> Could still slip in there, though less frequently 🤔 Maybe would need to catch; though can drop the `_isDisposed` field

Can also then make it a `readonly` struct

**Comment by LukaszRozmej** [comment]
> > `Cancel` is atomic with `IsCancellationRequested` and `Dispose` can be called multiple times, could you check that rather than `_isDisposed` and call cancel in `Dispose` to ensure ordering?
> 
> Could still slip in there, though less frequently 🤔 Maybe would need to catch; though can drop the `_isDisposed` field
> 
> ```cs
> public void Cancel()
> {
>     try
>     {
>         if (!Cancellation.IsCancellationRequested)
>         {
>             Cancellation.Cancel();
>         }
>     }
>     catch (ObjectDisposedException)
>     { 
>         // If Disposed has been cancelled
>     }
> }
> 
> public void Dispose()
> {
>     if (!Cancellation.IsCancellationRequested)
>     {
>         Cancellation.Cancel();
>     }
> 
>     Cancellation.Dispose();
> }
> ```

What is wrong with `lock` here? We expect race condition to happen very rarely here, so this lock won't affect performance in negative way. Acquiring the lock should be very fast.

**Comment by benaadams** [comment]
> What is wrong with lock here? We expect race condition to happen very rarely here, so this lock won't affect performance in negative way. Acquiring the lock should be very fast.

Nothing much though the lock will be held for the execution of all the cancellations.

`Dispose` itself unregisters all the cancellations and deactivates any associated timer; so you might still want to call Cancel in Dispose?

**Review by LukaszRozmej — APPROVED** [review]

**Pull request merged**
