### PR TITLE
Revise README and separate LICENSE files

### PR DESCRIPTION
**Pull request by rubo**
## Changes:

- The first paragraph of the README is revised to fix English issues and typos. `.NET Core` is replaced with `.NET`
- The LICENSE is split into two separate files for each license to allow GitHub [correctly handle](https://github.blog/changelog/2022-05-26-easily-discover-and-navigate-to-multiple-licenses-in-repositories/) them

## Types of changes

What types of changes does your code introduce?

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [x] Other (please describe): 

## Testing
**Requires testing**

- [ ] Yes
- [x] No

**In case you checked yes, did you write tests??**

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by LukaszRozmej — COMMENTED** [review]
AuRa is actually not a typo, but one of potential spelling :)

**Comment by rubo** [comment]
@LukaszRozmej That's right. I just used the one they use on their website as its no longer an acronym buy derived from AuRo.

**Comment by LukaszRozmej** [comment]
btw now we have 2x licences? I'm confused

**Comment by rubo** [comment]
Yes, we do. See the current [license](https://github.com/NethermindEth/nethermind/blob/master/LICENSE). Like [Geth](https://github.com/ethereum/go-ethereum). It's dual licensed with GPL/LGPL.

**Review by LukaszRozmej — APPROVED** [review]

**Pull request merged**
