### PR TITLE
Disconnect timed out connects

### LINKED ISSUE #6465: too many close_wait
Description
We are experiencing a high number of CLOSE_WAIT statuses on our Nethermind node. As observed using the command netstat -an | grep -i wait | wc -l, the count is at 1335. This issue indicates that while the remote client has closed the connection, our server-side Nethermind process has not yet acknowledged this closure, leading to a potential resource exhaustion.

Steps to Reproduce
To replicate this issue, follow these steps:

Run the Nethermind node normally.
After some uptime, execute the command netstat -an | grep -i wait | wc -l to check the number of CLOSE_WAIT connections.
Observe the number of connections that are in the CLOSE_WAIT status.
Actual behavior
Upon executing the above steps, we observe a high number of CLOSE_WAIT statuses (1335). This is concerning as it suggests that the Nethermind node is not properly closing connections, leading to potential memory and resource leaks.

Expected behavior
The expected behavior is that after a client closes a connection, the Nethermind node should properly close its end of the connection too, resulting in a very low number of CLOSE_WAIT statuses, ideally close to zero.

Screenshots
N/A (This issue is related to server-side network connection statuses and might not be adequately captured in screenshots.)

Desktop (please complete the following information):

Operating System: Ubuntu 22.04
Nethermind Version: 1.24.0
Installation Method: systemd
Consensus Client: Lighthouse v4.5.0

Additional context
This issue seems to manifest after the node has been running for an extended period, suggesting it might be related to how long-running connections are managed.

Logs
2024-01-06 13:34:49.3910|INFO|Consensus.Processing.BlockchainProcessor|24|- Block throughput   82.99 MGas/s |   1014.21 t/s |          7.99 Blk/s | recv        0 | proc        0 
2024-01-06 13:34:49.5910|INFO|Merge.Plugin.Handlers.ForkchoiceUpdatedHandler|94|Received ForkChoice: Head: 18949949 (0x451f3c...0eb329), Safe: 18949897 (0x176809...735e60), Finalized: 18949866 (0x398d75...5462d8) 
2024-01-06 13:34:49.5910|INFO|Merge.Plugin.Handlers.ForkchoiceUpdatedHandler|94|Synced chain Head to 18949949 (0x451f3c...0eb329) 
2024-01-06 13:34:57.9717|INFO|Network.PeerManager|5701|Removing 950 out of 10950 peer candidates (candidates cleanup). 
2024-01-06 13:34:58.9688|INFO|JsonRpc.JsonRpcLocalStats|5434|***** JSON RPC report *****
-------------------------------------------------------------------------------------------------------------------------------------------------------------
method                                  | successes |  avg time (µs) |  max time (µs) |    errors |  avg time (µs) |  max time (µs) | avg size | total size |
-------------------------------------------------------------------------------------------------------------------------------------------------------------
engine_forkchoiceUpdatedV2              |        26 |          40568 |         981417 |         0 |              0 |              0 |        0 |          0 | 
engine_getPayloadBodiesByRangeV1        |        56 |         375044 |        1270799 |         0 |              0 |              0 |        0 |          0 | 
engine_newPayloadV2                     |        25 |         488666 |         932409 |         0 |              0 |              0 |        0 |          0 | 
eth_chainId                             |         5 |            145 |            178 |         0 |              0 |              0 |        0 |          0 | 
eth_getBlockByNumber                    |        30 |          35266 |         402499 |         0 |              0 |              0 |        0 |          0 | 
eth_getLogs                             |         5 |          13135 |          44512 |         0 |              0 |              0 |        0 |          0 | 
eth_syncing                             |        25 |            167 |            328 |         0 |              0 |              0 |        0 |          0 | 
-------------------------------------------------------------------------------------------------------------------------------------------------------------
TOTAL                                   |       172 |         205828 |        1270799 |         0 |              0 |              0 |        0 |          0 | 
-------------------------------------------------------------------------------------------------------------------------------------------------------------
 
2024-01-06 13:35:00.3859|INFO|Merge.Plugin.Handlers.NewPayloadHandler|5434|Received new block:  18949950 (0xdcbe11...d6ed57) 
2024-01-06 13:35:00.5735|INFO|Consensus.Processing.BlockchainProcessor|24|Processed            18949950     |    185.53 ms  |  slot     11,183 ms | Gas gwei: 18.53 .. 18.53 (19.96) .. 33.41 
2024-01-06 13:35:00.5735|INFO|Consensus.Processing.BlockchainProcessor|24|- Block              12.14 MGas   |    135    txs |  calls    603 ( 13) | sload   2,109 | sstore    685 | create   0 
2024-01-06 13:35:00.5735|INFO|Consensus.Processing.BlockchainProcessor|24|- Block throughput   65.45 MGas/s |    727.64 t/s |          5.39 Blk/s | recv        0 | proc        0 
2024-01-06 13:35:00.7823|INFO|Merge.Plugin.Handlers.ForkchoiceUpdatedHandler|662|Received ForkChoice: Head: 18949950 (0xdcbe11...d6ed57), Safe: 18949897 (0x176809...735e60), Finalized: 18949866 (0x398d75...5462d8) 
2024-01-06 13:35:00.7823|INFO|Merge.Plugin.Handlers.ForkchoiceUpdatedHandler|662|Synced chain Head to 18949950 (0xdcbe11...d6ed57) 
2024-01-06 13:35:06.0722|INFO|Synchronization.Reporting.SyncReport|366|Peers | with best block: 101 | all: 101 | eth66 (4 %), eth67 (4 %), eth68 (92 %) | Active: None | Sleeping: All | Geth (52 %), Nethermind (37 %), Besu (5 %), Erigon (3 %), Reth (2 %), Unknown (1 %) 
2024-01-06 13:35:13.2348|INFO|Merge.Plugin.Handlers.NewPayloadHandler|94|Received new block:  18949951 (0xa9cdaf...6b352c) 
2024-01-06 13:35:13.5748|INFO|Consensus.Processing.BlockchainProcessor|24|Processed            18949951     |    337.59 ms  |  slot     13,001 ms | Gas gwei: 18.09 .. 18.22 (20.25) .. 64.90 
2024

### PR DESCRIPTION
**Pull request by benaadams**
Resolves #6465 

## Changes

- If connect timesout; cancel/close the connecting socket

#### What types of changes does your code introduce?

- [x] Bugfix (a non-breaking change that fixes an issue)

#### Requires testing

- [x] No

### CODE REVIEW

**Review by LukaszRozmej — COMMENTED** [review]
So in the end we do connect, weird, should we try to recover the connection?

**Comment by benaadams** [comment]
> So in the end we do connect, weird, should we try to recover the connection?

🤷‍♂️ Shouldn't leave a floating socket hanging aroud in the ether; just because the timeout finishes doesn't me the socket doesn't connect eventually

**Comment by LukaszRozmej** [comment]
> > So in the end we do connect, weird, should we try to recover the connection?
> 
> 🤷‍♂️ Shouldn't leave a floating socket hanging aroud in the ether; just because the timeout finishes doesn't me the socket doesn't connect eventually

But it should timeout itself: https://github.com/NethermindEth/nethermind/pull/6594/files#diff-86b8218c02ef77c7e74cd114c0d6be18c976da957e6667d7bc9a2e2370ee1befR171

**Review by LukaszRozmej — APPROVED** [review]

**Comment by benaadams** [comment]
> > > So in the end we do connect, weird, should we try to recover the connection?
> > 
> > 
> > 🤷‍♂️ Shouldn't leave a floating socket hanging aroud in the ether; just because the timeout finishes doesn't me the socket doesn't connect eventually
> 
> But it should timeout itself: https://github.com/NethermindEth/nethermind/pull/6594/files#diff-86b8218c02ef77c7e74cd114c0d6be18c976da957e6667d7bc9a2e2370ee1befR171

Should still depose it

**Pull request merged**
