### PR TITLE
Creating PPA Package for recent Ubuntu versions

### PR DESCRIPTION
**Pull request by hshafiq99**
## Changes

- Adding PPA Package code for sedge
- Adding copy binaries code for creating packages for other ubuntu versions

#### What types of changes does your code introduce?

- [ ] Bugfix (a non-breaking change that fixes an issue)
- [x] New feature (a non-breaking change that adds functionality)
- [ ] Breaking change (a fix or a feature that would cause existing functionality not to work as expected)
- [ ] Documentation update
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional or API changes)
- [ ] Build-related changes
- [ ] Other: _description_ 

#### Requires testing

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by rubo — CHANGES_REQUESTED** [review]
PR #5182 demonstrates changes I'd like to apply here. Long story short, it fixes paths in the workflow, removes warnings introduced (e.g. missing Python version, etc.), adds step names for better readability, and unifies the code to be the same way as other scripts.
Also, I'm not sure pausing the workflow for an hour is the best option here. Why do we need it?

**Comment by rubo** [comment]
@FalcoXYZ The current flow already requires an approval for everything: Build -> Approve -> GitHub, Docker, Downloads, PPA. Do we need anything more?
There's also #5142 waiting for a review.

**Comment by FalcoXYZ** [comment]
@rubo The issue right now is that we create a Github release (draft) and automatically push PPA, downloads page and Docker afterwards. This will result in stuff like PPA not working properly as it relies on the github release, and if it is a draft it won't update to latest version. 
We should make it so that docker/ppa/downloads page is only run AFTER Github is fully released properly. (so not a draft) Hope that makes sense for you.

**Review by rubo — APPROVED** [review]

**Review by FalcoXYZ — APPROVED** [review]
LGTM. Added the required secret too. 
@rubo or @LukaszRozmej feel free to merge whenever.

**Pull request merged**
