### PR TITLE
Fix posdao tests

### PR DESCRIPTION
**Pull request by marcindsobczak**
## Changes

- change `BalanceZeroFilter` to not filter out ANY transactions because of zero balance of sender account
- remove zero fee check

We started failing POSDAO master tests after commit https://github.com/NethermindEth/nethermind/pull/5290

posdao run: https://github.com/NethermindEth/nethermind/actions/runs/4363851628/jobs/7630451828
(lines 931-942)
```
Error: JSON RPC result is undefined. Response text: {"jsonrpc":"2.0","error":{"code":-32010,"message":"InsufficientFunds, Balance is zero, cannot pay gas"},"id":1}
    at /home/runner/work/nethermind/nethermind/posdao-test-setup/utils/sendRequest.js:17:16
    at ChildProcess.exithandler (child_process.js:299:7)
    at ChildProcess.emit (events.js:314:20)
    at maybeClose (internal/child_process.js:1022:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
```
After reverting commit https://github.com/NethermindEth/nethermind/pull/5290 tests are passing:
https://github.com/NethermindEth/nethermind/actions/runs/4372125278

Tests expect us to accept transactions with zero balance if they are local.

In this PR I changed `BalanceZeroFilter` to not filter out local transactions because of zero balance of sender account.

After this change POSDAO master tests are still failing, but for different reason, on later stage:
```
  1) Check log of random seeds to find incorrect seed values
       file /home/runner/work/nethermind/nethermind/posdao-test-setup/data/node1/checkRandomSeed.log should be empty:

      There were errors in seed calculation, check checkRandomSeed.log for logs
      + expected - actual

      -false
      +true
      
      at Context.<anonymous> (test/04_random_seed.js:15:127)
      at processImmediate (internal/timers.js:461:21)
```

It was because of zero fee check. Removed it. Tests are passing now:
https://github.com/NethermindEth/nethermind/actions/runs/4375138762/jobs/7655463220

## Types of changes

- [x] Bugfix (a non-breaking change that fixes an issue)
- [ ] New feature (a non-breaking change that adds functionality)
- [ ] Breaking change (a change that causes existing functionality not to work as expected)
- [ ] Optimization
- [ ] Refactoring
- [ ] Documentation update
- [ ] Build-related changes
- [ ] Other: _Description_

#### Requires testing

- [x] Yes
- [ ] No

#### If yes, did you write tests?

- [x] Yes
- [ ] No

### CODE REVIEW

**Comment by marcindsobczak** [comment]
@LukaszRozmej @MarekM25 do you have any idea why we have this problem with seeds or how it is related to changes from https://github.com/NethermindEth/nethermind/pull/5290?
[checkRandomSeed.log](https://github.com/NethermindEth/nethermind/files/10930504/checkRandomSeed.log)
[checkRandomSeedDebug.log](https://github.com/NethermindEth/nethermind/files/10930507/checkRandomSeedDebug.log)
[nethermind.logs.txt](https://github.com/NethermindEth/nethermind/files/10930510/nethermind.logs.txt)
(seed file must be empty to pass tests)

**Review by LukaszRozmej — APPROVED** [review]

**Comment by marcindsobczak** [comment]
Ok I figured it out. We just need to change `BalanceZeroFilter` to not filter out ANY transactions because of zero balance of sender account. I will push changes and need to run one more test to ensure

**Comment by benaadams** [comment]
> Ok I figured it out. We just need to change `BalanceZeroFilter` to not filter out ANY transactions because of zero balance of sender account. I will push changes and need to run one more test to ensure

Then all the txns will fail due to no gas; so why add them?

**Comment by benaadams** [comment]
Local txns seems fair; but holding other pool txns with no balance is just making the node do work and expand memory with no value?

**Comment by benaadams** [comment]
Checking on a sync'd mainnet it does filter a fair bit before moving on to the more expensive filters
```
Txn Pool State (2,048 txns queued)
------------------------------------------------
Sent
* Transactions:                                0
* Hashes:                             10,350,235
------------------------------------------------
Total Received:                          558,602
------------------------------------------------
Discarded at Filter Stage:
1.  GasLimitTooHigh:                           0
2.  Too Low Fee:                         178,155
3.  Malformed                                  3
4.  Duplicate:                           145,122
5.  Unknown Sender:                            0
6.  Zero Balance:                         13,083    <----
7.  Balance < tx.value:                   32,689
8.  Nonce used:                           45,550
9.  Nonces skipped:                       43,387
10. Balance Too Low:                      26,674
11. Cannot Compete:                          266
------------------------------------------------
Validated via State:                     235,322
------------------------------------------------
Total Discarded:                         484,663
------------------------------------------------
Discard Ratios:
* Pre-state Discards:                 66.70140 %
* Received Discarded:                 86.76356 %
------------------------------------------------
Total Added:                              73,673
* Eip1559 Added:                          45,249
------------------------------------------------
Total Evicted:                            52,288
------------------------------------------------
Ratios:
* Eip1559 Transactions:               93.50649 %
* DarkPool Level1:                     0.64935 %
* DarkPool Level2:                     0.64935 %
------------------------------------------------
```

**Comment by marcindsobczak** [comment]
Generally agree with @benaadams  that this changes are not welcome for mainnet/most networks, just wanted to check what we need to do to pass POSDAO. Now we know that 2 filters are causing failures and can figure out better solution suited specifically for AuRa

**Review by LukaszRozmej — APPROVED** [review]

**Comment by benaadams** [comment]
> Merge?

Will kill a lot of benefits on mainnet 😥

**Comment by marcindsobczak** [comment]
> Merge?
Nooo, it's not a good change. We need to bring filters back and disable them only for AuRa. I'm thinking what is the best way to achive it

**Comment by marcindsobczak** [comment]
Closing in favor of https://github.com/NethermindEth/nethermind/pull/5415

**Pull request closed without merging**
