### PR TITLE
Fast Call to Non contract addresses

### PR DESCRIPTION
**Pull request by benaadams**
## Changes

- If a call is to a non-contract address; just transfer the value rather than constructing a full call frame 
    - between 1% to 10% of calls per block are to non-contract (i.e. effectively only ETH transfers)

#### What types of changes does your code introduce?

- [x] Optimization

#### Requires testing

- [x] No

### CODE REVIEW

**Comment by benaadams** [comment]
Hive tests pass https://github.com/NethermindEth/nethermind/actions/runs/9232345307

**Review by LukaszRozmej — COMMENTED** [review]
Would be good to run cosnesus hive tests

**Comment by benaadams** [comment]
> Would be good to run cosnesus hive tests

https://github.com/NethermindEth/nethermind/actions/runs/9237001249

Same 256 failures as the prewarm branch

https://github.com/NethermindEth/nethermind/actions/runs/9238390120

Checking master

**Comment by benaadams** [comment]
Consensus hive failures are recent EIP7610 tests https://github.com/ethereum/EIPs/pull/8161

**Review by LukaszRozmej — APPROVED** [review]

**Pull request merged**
