### PR TITLE
Fix flaky network tests

### PR DESCRIPTION
**Pull request by rubo**
## Changes

Fixed DotNetty's `IByteBuffer` release in unit tests.

#### What types of changes does your code introduce?

- [x] Bugfix (a non-breaking change that fixes an issue)
- [ ] New feature (a non-breaking change that adds functionality)
- [ ] Breaking change (a fix or a feature that would cause existing functionality not to work as expected)
- [ ] Documentation update
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional or API changes)
- [ ] Build-related changes
- [ ] Other: _description_ 

#### Requires testing

- [x] Yes
- [ ] No

#### If yes, did you write tests?

- [x] Yes
- [ ] No

#### Notes on testing

This highly likely fixes the ever-failing network tests as the problem is with GitHub Actions workflow and is hard to produce locally. Successfully tested on GitHub.

### CODE REVIEW

**Review by LukaszRozmej — COMMENTED** [review]
Why not call `Release` on the buffer at the end of the test?

**Comment by rubo** [comment]
@LukaszRozmej That's exactly what it does.

**Comment by LukaszRozmej** [comment]
No, it schedules to release it when thread dies. If thread is from threadpool, or reused it won't release.

**Comment by rubo** [comment]
@LukaszRozmej Yes, when the test suite ends, it will release. Obviously, it's better than failing a test. Your suggestion of manually releasing doesn't work.

**Comment by LukaszRozmej** [comment]
> @LukaszRozmej Yes, when the test suite ends, it will release. Obviously, it's better than failing a test. Your suggestion of manually releasing doesn't work.

Do you know why it might not work?

**Comment by rubo** [comment]
@LukaszRozmej We already have such solutions with `Setup/Teardown` elsewhere that fails randomly. Releasing in the test function also doesn't work. I just noticed other cases to apply this change, so I'm gonna test further.

**Pull request closed without merging**
