### PR TITLE
Don't check out submodules

### PR DESCRIPTION
**Pull request by rubo**
Fixes the broken CodeQL analysis workflow.

## Changes:
Removed submodules checkout from CodeQL analysis workflow.

## Types of changes

What types of changes does your code introduce?

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Other (please describe): 

## Testing
**Requires testing**

- [x] Yes
- [ ] No

**In case you checked yes, did you write tests??**

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by LukaszRozmej** [comment]
Can you explain the impact?

**Comment by rubo** [comment]
@LukaszRozmej as the description says:

> Fixes the broken CodeQL analysis workflow.

**Review by LukaszRozmej — APPROVED** [review]

**Comment by LukaszRozmej** [comment]
But there are tests in the EthereumTests repo that would not run, making the tests coverage incomplete without it?

**Comment by rubo** [comment]
@LukaszRozmej Does this workflow use Ethereum tests as well?

**Comment by rubo** [comment]
Looks like you're mixing this issue up with something else. This change addresses the workflow failure because of removed submodules. It's failing for a few months on release. And the PR targets the release branch, not the `master`.

**Review by LukaszRozmej — APPROVED** [review]

**Review by MarekM25 — APPROVED** [review]

**Pull request closed without merging**
