### PR TITLE
Less invasive CPU logging

### LINKED ISSUE #5528: Can't run five nethermind instances on the same machine
Reported by SeaMonkey: https://discord.com/channels/629004402170134531/629004402170134537/1091388913186263140

It must be some sort of limitation of .NET 7, but I'm having a heck of a time getting five instances of Nethermind to run concurrently now.  The fifth one that is launched keeps hanging at 
2023-03-31 11:44:01.6552|ChainSpecPath matched an embedded resource inside the binary. Loading chainspec from embedded resources instead of file!

If I close one of the other Nethermind processes and then restart that one, it runs fine.  It seems like a full system restart temporarily fixes it, and sometimes dotnet build-server shutdown seems to resolve it, but if anyone has any suggestions on an actual cause and solution, I'd appreciate it.

### PR DESCRIPTION
**Pull request by benaadams**
Resolves #5528

## Changes

- Lighter query just to check CPU type
- Previously would iterate all hardware on the machine and jam if it conflicted with some other hardware access
image

#### What types of changes does your code introduce?

- [x] Bugfix (a non-breaking change that fixes an issue)
- [ ] New feature (a non-breaking change that adds functionality)
- [ ] Breaking change (a change that causes existing functionality not to work as expected)
- [ ] Optimization
- [ ] Refactoring
- [ ] Documentation update
- [ ] Build-related changes
- [ ] Other: _Description_

#### Requires testing

- [x] Yes
- [ ] No

#### If yes, did you write tests?

- [ ] Yes
- [x] No

#### Notes on testing

Requires testing on Mac (don't have access to one)

### CODE REVIEW

**Comment by asdacap** [comment]
Works on M1 Mac. `2023-04-11 02:16:29.4335|CPU: Apple M1 Pro (8C8T)`

**Review by asdacap — APPROVED** [review]

**Comment by LukaszRozmej** [comment]
While it works, arn't we reinventing the wheel here, compared to existing nuget packages like: https://www.nuget.org/packages/Hardware.Info ?

**Comment by benaadams** [comment]
Issue with the `HardwareInformation` previously used is it went deep on hardware querying; 99.99% of which was then thrown away as its just to log the CPU info to the logger in info mode

**Comment by LukaszRozmej** [comment]
> > While it works, arn't we reinventing the wheel here, compared to existing nuget packages like: https://www.nuget.org/packages/Hardware.Info ?
> 
> 2 sec to 21 secs to query the CPU? https://github.com/Jinjinov/Hardware.Info

Yeah seems overkill, what about: https://github.com/iAJTin/iCPUID

**Pull request merged**
