### PR TITLE
Use Dynamic Profile-Guided Optimization

### PR DESCRIPTION
**Pull request by benaadams**
## Changes

Enable .NET 7.0 [Dynamic PGO](https://learn.microsoft.com/en-us/dotnet/core/whats-new/dotnet-7#performance) and on stack replacement 

Example of experiences in the wild https://petabridge.com/blog/dotnet7-pgo-performance-improvements/

#### What types of changes does your code introduce?

- [ ] Bugfix (a non-breaking change that fixes an issue)
- [ ] New feature (a non-breaking change that adds functionality)
- [ ] Breaking change (a change that causes existing functionality not to work as expected)
- [x] Optimization
- [ ] Refactoring
- [ ] Documentation update
- [ ] Build-related changes
- [ ] Other: _Description_

#### Requires testing

- [ ] Yes
- [x] No

#### If yes, did you write tests?

- [ ] Yes
- [ ] No

## Remarks

With this one weird trick

### CODE REVIEW

**Comment by flcl42** [comment]
Sync phase has a different profile than regular execution. Does PGO need to realign after sync?

**Comment by benaadams** [comment]
> Sync phase has a different profile than regular execution. Does PGO need to realign after sync?

It reprofiles on each restart; also for the lifetime of the running app. So as new methods are called it fast-Jit compiles them for fast startup; then after a number of calls will re-Jit them optimised using the data from those calls.

It doesn't de-optimise methods and move back to profiling them once they have been optimised however if that is the question. Presumably sync phase will be calling different methods than regular execution; rather than causing the same methods to execute completely differently? (e.g. use a different concrete class behind an interface)

**Comment by LukaszRozmej** [comment]
1. I assume it is sufficient to mark this on entry points to the app and not on every project?
2. Before merging this would benefit from some measurements in Benchmarks and Metrics @kamilchodola

**Comment by benaadams** [comment]
> 1. I assume it is sufficient to mark this on entry points to the app and not on every project?

Yes, only needs to be on the exe; not the libs

**Comment by benaadams** [comment]
> Yes, only needs to be on the exe; not the libs

It will re-optimise all the libs and exe, but not currently the runtime as that is already PGO optimised to a "ready to run" version. However in .NET 8; it will also revisit the runtime and reoptimize that for the running app with https://github.com/dotnet/runtime/pull/70941

**Review by rubo — APPROVED** [review]

**Comment by LukaszRozmej** [comment]
@kamilchodola do you want to test it in branch or should we merge it to master?

**Comment by kamilchodola** [comment]
I'd prefer merging it to master and test together with all changes for some time.

**Review by LukaszRozmej — APPROVED** [review]

**Pull request merged**
