### PR TITLE
Boost and fix tests

### PR DESCRIPTION
**Pull request by rubo**
## Changes

- Made tests run much faster. Parallelized all of them to speed them up and make them more reliable.
- Addressed DotNetty's memory leak warnings in tests
- Increased the number of retries for some tests
- For the sake of consistency, renamed `Nethermind.JsonRpc.TraceStore.Tests` and `Nethermind.Hive.Tests` to `Nethermind.JsonRpc.TraceStore.Test` and `Nethermind.Hive.Test` respectively (dropped trailing "s"). Hence, the number of files changed.

#### What types of changes does your code introduce?

- [x] Bugfix (a non-breaking change that fixes an issue)
- [ ] New feature (a non-breaking change that adds functionality)
- [ ] Breaking change (a change that causes existing functionality not to work as expected)
- [ ] Optimization
- [x] Refactoring
- [ ] Documentation update
- [ ] Build-related changes
- [x] Other: Infrastructure

#### Requires testing

- [x] Yes
- [ ] No

#### If yes, did you write tests?

- [x] Yes
- [ ] No

#### Notes on testing

Ran around 40 times. Tests look much faster and more stable.

## Remarks

Need to test further to check the behavior depending on the time. Still, there is [the infamous issue](https://github.com/microsoft/vstest/issues/3658) with the `vstest`.

### CODE REVIEW

**Review by smartprogrammer93 — APPROVED** [review]

**Comment by LukaszRozmej** [comment]
If you could also make it all pass in my rider on widnows :)

**Review by LukaszRozmej — APPROVED** [review]
Only problem I see is that we are renaming stuff again and it will be painfull to migrate existing PR's to new naming scheme with having required passes

**Comment by LukaszRozmej** [comment]
Nethermind.Synchronization.Test 13m 
Ethereum.Blockchain.Test 7m

Should they be broken down to be faster? Should they be moved to the top if there will be concurrency limit to be run first?

**Comment by rubo** [comment]
> Only problem I see is that we are renaming stuff again and it will be painfull to migrate existing PR's to new naming scheme with having required passes. Another downside is that adding new test project will require amending both the action as well as the repo requirements - there is no abstraction like it is now.

@LukaszRozmej Renaming is inevitable in this case. I don't consider it a problem as all you need to do is merging the `master` to your PR branches. But you made a good point about adding a new test suite. See below.

> Nethermind.Synchronization.Test 13m Ethereum.Blockchain.Test 7m
> 
> Should they be broken down to be faster? Should they be moved to the top if there will be concurrency limit to be run first?

@LukaszRozmej Maybe. I haven't checked their internal, so I don't know at the moment. Yes, that would help in case of any concurrency limitation. I sorted them alphabetically so we can easily find whatever we look up for or not miss one when checking.

Also, as I ended up with very similar test workflows with the only difference being code coverage, I'm gonna merge them into a single workflow and handle code coverage depending on conditions. For now, code coverage run takes around 6h and very often times out while this PR makes it completing within 2h or so. It takes so long because of the two tests you mentioned above. So there's room to improve it.

Now, merging these two workflows could conflict with our mandatory test requirements, so instead of making each of these test suites mandatory, I think about having some status jobs for that. So, under the PR there would be 2 required jobs instead of 50. Say

- Nethermind tests
- Ethereum tests

These would address your concern about adding new test suites as well. With this said, I'm gonna make this PR draft to experiment further.

BTW, do we really need Ethereum tests to be part of code coverage?

**Pull request merged**
